2019-04-29 14:30:40,325 - discord.client - WARNING - PyNaCl is not installed, voice will NOT be supported
2019-04-29 14:30:40,377 - db_handler - INFO - Init DB connection
2019-04-29 14:30:40,389 - db_handler - INFO - Init DB connection
2019-04-29 14:30:40,404 - discord.client - INFO - logging in using static token
2019-04-29 14:30:41,885 - discord.gateway - INFO - Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
2019-04-29 14:30:41,888 - discord.gateway - INFO - Shard ID None has sent the IDENTIFY payload.
2019-04-29 14:30:42,100 - discord.gateway - INFO - Shard ID None has connected to Gateway: gateway-prd-main-xsd1, discord-sessions-prd-1-14 (Session ID: 9ade061afa0bd6f114db1c4fe77a1d27).
2019-04-29 14:31:10,068 - db_handler - INFO - User Deesnow#0840 added to the MongoDB
2019-04-29 14:45:33,658 - discord.client - WARNING - PyNaCl is not installed, voice will NOT be supported
2019-04-29 14:45:33,661 - db_handler - INFO - Init DB connection
2019-04-29 14:45:33,669 - db_handler - INFO - Init DB connection
2019-04-29 14:45:33,688 - discord.client - INFO - logging in using static token
2019-04-29 14:45:34,743 - discord.gateway - INFO - Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
2019-04-29 14:45:34,745 - discord.gateway - INFO - Shard ID None has sent the IDENTIFY payload.
2019-04-29 14:45:34,920 - discord.gateway - INFO - Shard ID None has connected to Gateway: gateway-prd-main-jjz2, discord-sessions-prd-1-26 (Session ID: eae3b9a4255cd18ce649d8ec72c11c91).
2019-04-29 14:48:22,347 - __main__ - ERROR - cmdGetLink cannot be unloaded. [Extension 'cmdGetLink' has not been loaded.]
Traceback (most recent call last):
  File "f:\_DEV\Discord\SnakeBot\__main__.py", line 64, in unload
    bot.unload_extension(extension)
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\discord\ext\commands\bot.py", line 650, in unload_extension
    raise errors.ExtensionNotLoaded(name)
discord.ext.commands.errors.ExtensionNotLoaded: Extension 'cmdGetLink' has not been loaded.
2019-04-29 14:48:41,076 - __main__ - ERROR - cmdGetLink cannot be loaded. [Extension 'cmdGetLink' could not be loaded.]
Traceback (most recent call last):
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\discord\ext\commands\bot.py", line 618, in load_extension
    lib = importlib.import_module(name)
  File "F:\_DEV\Envs\SnakeBot\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 948, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'cmdGetLink'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "f:\_DEV\Discord\SnakeBot\__main__.py", line 53, in load
    bot.load_extension(extension)
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\discord\ext\commands\bot.py", line 620, in load_extension
    raise errors.ExtensionNotFound(name, e) from e
discord.ext.commands.errors.ExtensionNotFound: Extension 'cmdGetLink' could not be loaded.
2019-04-29 15:50:51,844 - discord.client - WARNING - PyNaCl is not installed, voice will NOT be supported
2019-04-29 15:50:51,860 - db_handler - INFO - Init DB connection
2019-04-29 15:50:51,869 - db_handler - INFO - Init DB connection
2019-04-29 15:50:52,046 - db_handler - INFO - Init DB connection
2019-04-29 15:50:52,052 - discord.client - INFO - logging in using static token
2019-04-29 15:50:53,603 - discord.gateway - INFO - Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
2019-04-29 15:50:53,606 - discord.gateway - INFO - Shard ID None has sent the IDENTIFY payload.
2019-04-29 15:50:53,754 - discord.gateway - INFO - Shard ID None has connected to Gateway: gateway-prd-main-h5b1, discord-sessions-prd-1-17 (Session ID: 4f7f9353389922c8e3548de30a0c4701).
2019-04-29 15:52:27,436 - db_handler - INFO - Init DB connection
2019-04-29 15:52:51,141 - db_handler - ERROR - Get allycode is FAILED. 'str' object has no attribute 'formant'
Traceback (most recent call last):
  File "f:\_DEV\Discord\SnakeBot\db_handler.py", line 116, in get_allycode
    self.logger.info('{} found for {}'.formant(self.allycode, self.user_id))
AttributeError: 'str' object has no attribute 'formant'
2019-04-29 15:52:51,806 - swgoh_handler - INFO - Response 200 OK
2019-04-29 15:52:51,806 - swgoh_handler - ERROR - GET url is failed - [Expecting value: line 2 column 1 (char 1)]
Traceback (most recent call last):
  File "f:\_DEV\Discord\SnakeBot\swgoh_handler.py", line 25, in swgoh_getuser
    return json.loads(self.response.text)
  File "d:\python3.6-64\Lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "d:\python3.6-64\Lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "d:\python3.6-64\Lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 1)
2019-04-29 15:57:23,117 - discord.client - WARNING - PyNaCl is not installed, voice will NOT be supported
2019-04-29 15:57:23,124 - db_handler - INFO - Init DB connection
2019-04-29 15:57:23,141 - db_handler - INFO - Init DB connection
2019-04-29 15:57:23,400 - discord.client - INFO - logging in using static token
2019-04-29 15:57:24,485 - discord.gateway - INFO - Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
2019-04-29 15:57:24,499 - discord.gateway - INFO - Shard ID None has sent the IDENTIFY payload.
2019-04-29 15:57:25,108 - discord.gateway - INFO - Shard ID None has connected to Gateway: gateway-prd-main-kccm, discord-sessions-prd-1-28 (Session ID: ea2a32958406b3a2481f5654961c514c).
2019-04-29 15:59:20,023 - discord.client - WARNING - PyNaCl is not installed, voice will NOT be supported
2019-04-29 15:59:20,037 - db_handler - INFO - Init DB connection
2019-04-29 15:59:20,065 - db_handler - INFO - Init DB connection
2019-04-29 15:59:20,422 - discord.client - INFO - logging in using static token
2019-04-29 15:59:21,597 - discord.gateway - INFO - Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
2019-04-29 15:59:21,606 - discord.gateway - INFO - Shard ID None has sent the IDENTIFY payload.
2019-04-29 15:59:21,757 - discord.gateway - INFO - Shard ID None has connected to Gateway: gateway-prd-main-9xgj, discord-sessions-prd-1-19 (Session ID: 5ce2f081f9297e654c16ae1df0735ddb).
2019-04-29 16:02:27,445 - discord.client - WARNING - PyNaCl is not installed, voice will NOT be supported
2019-04-29 16:02:27,455 - db_handler - INFO - Init DB connection
2019-04-29 16:02:27,498 - db_handler - INFO - Init DB connection
2019-04-29 16:02:27,777 - discord.client - INFO - logging in using static token
2019-04-29 16:02:28,847 - discord.gateway - INFO - Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
2019-04-29 16:02:28,854 - discord.gateway - INFO - Shard ID None has sent the IDENTIFY payload.
2019-04-29 16:02:29,031 - discord.gateway - INFO - Shard ID None has connected to Gateway: gateway-prd-main-zsf1, discord-sessions-prd-1-13 (Session ID: dde0aa8d33f5bc8236aa203b39e7d000).
2019-04-29 16:04:09,382 - discord.client - WARNING - PyNaCl is not installed, voice will NOT be supported
2019-04-29 16:04:09,385 - db_handler - INFO - Init DB connection
2019-04-29 16:04:09,392 - db_handler - INFO - Init DB connection
2019-04-29 16:04:09,557 - discord.client - INFO - logging in using static token
2019-04-29 16:04:10,607 - discord.gateway - INFO - Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
2019-04-29 16:04:10,639 - discord.gateway - INFO - Shard ID None has sent the IDENTIFY payload.
2019-04-29 16:04:10,794 - discord.gateway - INFO - Shard ID None has connected to Gateway: gateway-prd-main-fgf7, discord-sessions-prd-1-8 (Session ID: 543505e921ef231d31d9e9a33ae195ad).
2019-04-29 16:08:27,814 - discord.client - WARNING - PyNaCl is not installed, voice will NOT be supported
2019-04-29 16:08:27,824 - db_handler - INFO - Init DB connection
2019-04-29 16:08:27,840 - db_handler - INFO - Init DB connection
2019-04-29 16:08:28,110 - db_handler - INFO - Init DB connection
2019-04-29 16:08:28,132 - discord.client - INFO - logging in using static token
2019-04-29 16:08:29,259 - discord.gateway - INFO - Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
2019-04-29 16:08:29,267 - discord.gateway - INFO - Shard ID None has sent the IDENTIFY payload.
2019-04-29 16:08:29,429 - discord.gateway - INFO - Shard ID None has connected to Gateway: gateway-prd-main-8h8j, discord-sessions-prd-1-28 (Session ID: d3e874f32c09af5fc6889fb93630e021).
2019-04-29 16:09:15,518 - discord.gateway - WARNING - Heartbeat blocked for more than 5 seconds.
2019-04-29 16:09:20,522 - discord.gateway - WARNING - Heartbeat blocked for more than 10 seconds.
2019-04-29 16:09:25,529 - discord.gateway - WARNING - Heartbeat blocked for more than 15 seconds.
2019-04-29 16:09:30,531 - discord.gateway - WARNING - Heartbeat blocked for more than 20 seconds.
2019-04-29 16:09:35,534 - discord.gateway - WARNING - Heartbeat blocked for more than 25 seconds.
2019-04-29 16:09:40,540 - discord.gateway - WARNING - Heartbeat blocked for more than 30 seconds.
2019-04-29 16:09:45,544 - discord.gateway - WARNING - Heartbeat blocked for more than 35 seconds.
2019-04-29 16:09:46,303 - db_handler - ERROR - Get allycode is FAILED. 'str' object has no attribute 'formant'
Traceback (most recent call last):
  File "f:\_DEV\Discord\SnakeBot\db_handler.py", line 116, in get_allycode
    self.logger.info('{} found for {}'.formant(self.allycode, self.user_id))
AttributeError: 'str' object has no attribute 'formant'
2019-04-29 16:09:50,548 - discord.gateway - WARNING - Heartbeat blocked for more than 40 seconds.
2019-04-29 16:09:55,586 - discord.gateway - WARNING - Heartbeat blocked for more than 45 seconds.
2019-04-29 16:10:00,597 - discord.gateway - WARNING - Heartbeat blocked for more than 50 seconds.
2019-04-29 16:10:05,599 - discord.gateway - WARNING - Heartbeat blocked for more than 55 seconds.
2019-04-29 16:10:10,604 - discord.gateway - WARNING - Heartbeat blocked for more than 60 seconds.
2019-04-29 16:10:15,607 - discord.gateway - WARNING - Heartbeat blocked for more than 65 seconds.
2019-04-29 16:12:57,456 - discord.client - WARNING - PyNaCl is not installed, voice will NOT be supported
2019-04-29 16:12:57,462 - db_handler - INFO - Init DB connection
2019-04-29 16:12:57,490 - db_handler - INFO - Init DB connection
2019-04-29 16:12:57,792 - db_handler - INFO - Init DB connection
2019-04-29 16:12:57,828 - discord.client - INFO - logging in using static token
2019-04-29 16:12:59,017 - discord.gateway - INFO - Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
2019-04-29 16:12:59,027 - discord.gateway - INFO - Shard ID None has sent the IDENTIFY payload.
2019-04-29 16:12:59,185 - discord.gateway - INFO - Shard ID None has connected to Gateway: gateway-prd-main-gfs7, discord-sessions-prd-1-19 (Session ID: 95835d036e706dc87df53d634368e1ab).
2019-04-29 16:13:45,278 - discord.gateway - WARNING - Heartbeat blocked for more than 5 seconds.
2019-04-29 16:13:50,281 - discord.gateway - WARNING - Heartbeat blocked for more than 10 seconds.
2019-04-29 16:13:55,284 - discord.gateway - WARNING - Heartbeat blocked for more than 15 seconds.
2019-04-29 16:14:00,286 - discord.gateway - WARNING - Heartbeat blocked for more than 20 seconds.
2019-04-29 16:14:05,291 - discord.gateway - WARNING - Heartbeat blocked for more than 25 seconds.
2019-04-29 16:14:10,294 - discord.gateway - WARNING - Heartbeat blocked for more than 30 seconds.
2019-04-29 16:14:15,296 - discord.gateway - WARNING - Heartbeat blocked for more than 35 seconds.
2019-04-29 16:14:20,302 - discord.gateway - WARNING - Heartbeat blocked for more than 40 seconds.
2019-04-29 16:14:25,305 - discord.gateway - WARNING - Heartbeat blocked for more than 45 seconds.
2019-04-29 16:14:30,312 - discord.gateway - WARNING - Heartbeat blocked for more than 50 seconds.
2019-04-29 16:14:35,316 - discord.gateway - WARNING - Heartbeat blocked for more than 55 seconds.
2019-04-29 16:14:40,322 - discord.gateway - WARNING - Heartbeat blocked for more than 60 seconds.
2019-04-29 16:14:45,327 - discord.gateway - WARNING - Heartbeat blocked for more than 65 seconds.
2019-04-29 16:14:50,330 - discord.gateway - WARNING - Heartbeat blocked for more than 70 seconds.
2019-04-29 16:14:55,339 - discord.gateway - WARNING - Heartbeat blocked for more than 75 seconds.
2019-04-29 16:15:00,342 - discord.gateway - WARNING - Heartbeat blocked for more than 80 seconds.
2019-04-29 16:15:05,345 - discord.gateway - WARNING - Heartbeat blocked for more than 85 seconds.
2019-04-29 16:15:10,347 - discord.gateway - WARNING - Heartbeat blocked for more than 90 seconds.
2019-04-29 16:15:15,350 - discord.gateway - WARNING - Heartbeat blocked for more than 95 seconds.
2019-04-29 16:15:20,352 - discord.gateway - WARNING - Heartbeat blocked for more than 100 seconds.
2019-04-29 16:15:25,358 - discord.gateway - WARNING - Heartbeat blocked for more than 105 seconds.
2019-04-29 16:15:30,362 - discord.gateway - WARNING - Heartbeat blocked for more than 110 seconds.
2019-04-29 16:15:35,367 - discord.gateway - WARNING - Heartbeat blocked for more than 115 seconds.
2019-04-29 16:15:40,372 - discord.gateway - WARNING - Heartbeat blocked for more than 120 seconds.
2019-04-29 16:15:43,765 - db_handler - INFO - {'ally_code': 376764962} found for 143651954919342080
2019-04-29 16:15:45,378 - discord.gateway - WARNING - Heartbeat blocked for more than 125 seconds.
2019-04-29 16:15:50,384 - discord.gateway - WARNING - Heartbeat blocked for more than 130 seconds.
2019-04-29 16:15:55,387 - discord.gateway - WARNING - Heartbeat blocked for more than 135 seconds.
2019-04-29 16:16:00,395 - discord.gateway - WARNING - Heartbeat blocked for more than 140 seconds.
2019-04-29 16:16:05,398 - discord.gateway - WARNING - Heartbeat blocked for more than 145 seconds.
2019-04-29 16:16:10,402 - discord.gateway - WARNING - Heartbeat blocked for more than 150 seconds.
2019-04-29 16:16:15,406 - discord.gateway - WARNING - Heartbeat blocked for more than 155 seconds.
2019-04-29 16:16:20,409 - discord.gateway - WARNING - Heartbeat blocked for more than 160 seconds.
2019-04-29 16:16:25,412 - discord.gateway - WARNING - Heartbeat blocked for more than 165 seconds.
2019-04-29 16:16:30,415 - discord.gateway - WARNING - Heartbeat blocked for more than 170 seconds.
2019-04-29 16:16:35,418 - discord.gateway - WARNING - Heartbeat blocked for more than 175 seconds.
2019-04-29 16:16:40,425 - discord.gateway - WARNING - Heartbeat blocked for more than 180 seconds.
2019-04-29 16:16:45,428 - discord.gateway - WARNING - Heartbeat blocked for more than 185 seconds.
2019-04-29 16:17:20,802 - discord.client - WARNING - PyNaCl is not installed, voice will NOT be supported
2019-04-29 16:17:20,810 - db_handler - INFO - Init DB connection
2019-04-29 16:17:20,834 - db_handler - INFO - Init DB connection
2019-04-29 16:17:21,116 - db_handler - INFO - Init DB connection
2019-04-29 16:17:21,148 - discord.client - INFO - logging in using static token
2019-04-29 16:17:22,294 - discord.gateway - INFO - Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
2019-04-29 16:17:22,307 - discord.gateway - INFO - Shard ID None has sent the IDENTIFY payload.
2019-04-29 16:17:22,452 - discord.gateway - INFO - Shard ID None has connected to Gateway: gateway-prd-main-rfj9, discord-sessions-prd-1-24 (Session ID: a322dbf2675d61d68ddb755be74ca39b).
2019-04-29 16:17:53,452 - db_handler - INFO - {'ally_code': 376764962} found for 143651954919342080
2019-04-29 16:18:08,562 - discord.gateway - WARNING - Heartbeat blocked for more than 5 seconds.
2019-04-29 16:18:13,566 - discord.gateway - WARNING - Heartbeat blocked for more than 10 seconds.
2019-04-29 16:18:18,570 - discord.gateway - WARNING - Heartbeat blocked for more than 15 seconds.
2019-04-29 16:18:23,575 - discord.gateway - WARNING - Heartbeat blocked for more than 20 seconds.
2019-04-29 16:18:28,577 - discord.gateway - WARNING - Heartbeat blocked for more than 25 seconds.
2019-04-29 16:18:33,583 - discord.gateway - WARNING - Heartbeat blocked for more than 30 seconds.
2019-04-29 16:18:38,590 - discord.gateway - WARNING - Heartbeat blocked for more than 35 seconds.
2019-04-29 16:18:43,599 - discord.gateway - WARNING - Heartbeat blocked for more than 40 seconds.
2019-04-29 16:18:48,612 - discord.gateway - WARNING - Heartbeat blocked for more than 45 seconds.
2019-04-29 16:18:53,615 - discord.gateway - WARNING - Heartbeat blocked for more than 50 seconds.
2019-04-29 16:18:58,621 - discord.gateway - WARNING - Heartbeat blocked for more than 55 seconds.
2019-04-29 16:19:03,628 - discord.gateway - WARNING - Heartbeat blocked for more than 60 seconds.
2019-04-29 16:19:08,635 - discord.gateway - WARNING - Heartbeat blocked for more than 65 seconds.
2019-04-29 16:19:13,640 - discord.gateway - WARNING - Heartbeat blocked for more than 70 seconds.
2019-04-29 16:19:18,642 - discord.gateway - WARNING - Heartbeat blocked for more than 75 seconds.
2019-04-29 16:19:23,653 - discord.gateway - WARNING - Heartbeat blocked for more than 80 seconds.
2019-04-29 16:19:27,510 - swgoh_handler - INFO - Response 200 OK
2019-04-29 16:19:28,656 - discord.gateway - WARNING - Heartbeat blocked for more than 85 seconds.
2019-04-29 16:19:33,660 - discord.gateway - WARNING - Heartbeat blocked for more than 90 seconds.
2019-04-29 16:19:38,662 - discord.gateway - WARNING - Heartbeat blocked for more than 95 seconds.
2019-04-29 16:19:43,665 - discord.gateway - WARNING - Heartbeat blocked for more than 100 seconds.
2019-04-29 16:19:48,668 - discord.gateway - WARNING - Heartbeat blocked for more than 105 seconds.
2019-04-29 16:19:53,671 - discord.gateway - WARNING - Heartbeat blocked for more than 110 seconds.
2019-04-29 16:19:58,680 - discord.gateway - WARNING - Heartbeat blocked for more than 115 seconds.
2019-04-29 16:20:02,147 - discord.gateway - INFO - Websocket closed with 1000 (), cannot reconnect.
2019-04-29 16:20:02,150 - discord.client - ERROR - Attempting a reconnect in 0.84s
Traceback (most recent call last):
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\discord\gateway.py", line 464, in poll_event
    msg = await self.recv()
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\websockets\protocol.py", line 350, in recv
    yield from self.ensure_open()
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\websockets\protocol.py", line 501, in ensure_open
    self.close_code, self.close_reason) from self.transfer_data_exc
websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1000 (OK), no reason

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\discord\client.py", line 431, in connect
    await self._connect()
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\discord\client.py", line 395, in _connect
    await self.ws.poll_event()
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\discord\gateway.py", line 472, in poll_event
    raise ConnectionClosed(exc, shard_id=self.shard_id) from exc
discord.errors.ConnectionClosed: WebSocket connection is closed: code = 1000 (OK), no reason
2019-04-29 16:20:03,385 - discord.gateway - INFO - Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
2019-04-29 16:20:03,398 - discord.gateway - INFO - Shard ID None has sent the IDENTIFY payload.
2019-04-29 16:20:03,542 - discord.gateway - INFO - Shard ID None has connected to Gateway: gateway-prd-main-5lgk, discord-sessions-prd-1-12 (Session ID: 58f80969733ccc0eaa12be63072517cd).
2019-04-29 16:20:43,398 - discord.gateway - WARNING - Shard ID None has stopped responding to the gateway. Closing and restarting.
2019-04-29 16:21:40,252 - db_handler - INFO - Init DB connection
2019-04-29 16:21:51,704 - db_handler - INFO - {'ally_code': 376764962} found for 143651954919342080
2019-04-29 16:21:52,424 - swgoh_handler - INFO - Response 200 OK
2019-04-29 16:23:23,662 - db_handler - INFO - Init DB connection
2019-04-29 16:23:29,072 - db_handler - INFO - {'ally_code': 376764962} found for 143651954919342080
2019-04-29 16:23:34,681 - discord.gateway - WARNING - Heartbeat blocked for more than 5 seconds.
2019-04-29 16:23:39,684 - discord.gateway - WARNING - Heartbeat blocked for more than 10 seconds.
2019-04-29 16:23:44,685 - discord.gateway - WARNING - Heartbeat blocked for more than 15 seconds.
2019-04-29 16:23:49,691 - discord.gateway - WARNING - Heartbeat blocked for more than 20 seconds.
2019-04-29 16:23:54,701 - discord.gateway - WARNING - Heartbeat blocked for more than 25 seconds.
2019-04-29 16:23:59,702 - discord.gateway - WARNING - Heartbeat blocked for more than 30 seconds.
2019-04-29 16:24:04,705 - discord.gateway - WARNING - Heartbeat blocked for more than 35 seconds.
2019-04-29 16:24:05,367 - swgoh_handler - INFO - Response 200 OK
2019-04-29 16:24:09,708 - discord.gateway - WARNING - Heartbeat blocked for more than 40 seconds.
2019-04-29 16:24:14,717 - discord.gateway - WARNING - Heartbeat blocked for more than 45 seconds.
2019-04-29 16:24:19,719 - discord.gateway - WARNING - Heartbeat blocked for more than 50 seconds.
2019-04-29 16:24:24,721 - discord.gateway - WARNING - Heartbeat blocked for more than 55 seconds.
2019-04-29 16:24:29,723 - discord.gateway - WARNING - Heartbeat blocked for more than 60 seconds.
2019-04-29 16:24:34,729 - discord.gateway - WARNING - Heartbeat blocked for more than 65 seconds.
2019-04-29 16:24:39,731 - discord.gateway - WARNING - Heartbeat blocked for more than 70 seconds.
2019-04-29 16:24:44,737 - discord.gateway - WARNING - Heartbeat blocked for more than 75 seconds.
2019-04-29 16:24:49,739 - discord.gateway - WARNING - Heartbeat blocked for more than 80 seconds.
2019-04-29 16:24:54,743 - discord.gateway - WARNING - Heartbeat blocked for more than 85 seconds.
2019-04-29 16:24:59,744 - discord.gateway - WARNING - Heartbeat blocked for more than 90 seconds.
2019-04-29 16:25:04,749 - discord.gateway - WARNING - Heartbeat blocked for more than 95 seconds.
2019-04-29 16:25:09,753 - discord.gateway - WARNING - Heartbeat blocked for more than 100 seconds.
2019-04-29 16:25:14,757 - discord.gateway - WARNING - Heartbeat blocked for more than 105 seconds.
2019-04-29 16:25:19,763 - discord.gateway - WARNING - Heartbeat blocked for more than 110 seconds.
2019-04-29 16:25:24,769 - discord.gateway - WARNING - Heartbeat blocked for more than 115 seconds.
2019-04-29 16:25:29,776 - discord.gateway - WARNING - Heartbeat blocked for more than 120 seconds.
2019-04-29 16:25:34,784 - discord.gateway - WARNING - Heartbeat blocked for more than 125 seconds.
2019-04-29 16:25:39,786 - discord.gateway - WARNING - Heartbeat blocked for more than 130 seconds.
2019-04-29 16:25:44,789 - discord.gateway - WARNING - Heartbeat blocked for more than 135 seconds.
2019-04-29 16:25:49,793 - discord.gateway - WARNING - Heartbeat blocked for more than 140 seconds.
2019-04-29 16:25:54,799 - discord.gateway - WARNING - Heartbeat blocked for more than 145 seconds.
2019-04-29 16:25:59,802 - discord.gateway - WARNING - Heartbeat blocked for more than 150 seconds.
2019-04-29 16:26:04,809 - discord.gateway - WARNING - Heartbeat blocked for more than 155 seconds.
2019-04-29 16:26:09,816 - discord.gateway - WARNING - Heartbeat blocked for more than 160 seconds.
2019-04-29 16:26:14,820 - discord.gateway - WARNING - Heartbeat blocked for more than 165 seconds.
2019-04-29 16:26:19,822 - discord.gateway - WARNING - Heartbeat blocked for more than 170 seconds.
2019-04-29 16:26:24,826 - discord.gateway - WARNING - Heartbeat blocked for more than 175 seconds.
2019-04-29 16:26:29,837 - discord.gateway - WARNING - Heartbeat blocked for more than 180 seconds.
2019-04-29 16:26:34,843 - discord.gateway - WARNING - Heartbeat blocked for more than 185 seconds.
2019-04-29 16:26:39,845 - discord.gateway - WARNING - Heartbeat blocked for more than 190 seconds.
2019-04-29 16:26:44,850 - discord.gateway - WARNING - Heartbeat blocked for more than 195 seconds.
2019-04-29 16:26:49,859 - discord.gateway - WARNING - Heartbeat blocked for more than 200 seconds.
2019-04-29 16:26:54,861 - discord.gateway - WARNING - Heartbeat blocked for more than 205 seconds.
2019-04-29 16:26:59,866 - discord.gateway - WARNING - Heartbeat blocked for more than 210 seconds.
2019-04-29 16:27:04,869 - discord.gateway - WARNING - Heartbeat blocked for more than 215 seconds.
2019-04-29 16:27:09,874 - discord.gateway - WARNING - Heartbeat blocked for more than 220 seconds.
2019-04-29 16:27:14,878 - discord.gateway - WARNING - Heartbeat blocked for more than 225 seconds.
2019-04-29 16:27:19,880 - discord.gateway - WARNING - Heartbeat blocked for more than 230 seconds.
2019-04-29 16:27:24,883 - discord.gateway - WARNING - Heartbeat blocked for more than 235 seconds.
2019-04-29 16:27:29,888 - discord.gateway - WARNING - Heartbeat blocked for more than 240 seconds.
2019-04-29 16:27:34,890 - discord.gateway - WARNING - Heartbeat blocked for more than 245 seconds.
2019-04-29 16:27:39,895 - discord.gateway - WARNING - Heartbeat blocked for more than 250 seconds.
2019-04-29 16:27:44,901 - discord.gateway - WARNING - Heartbeat blocked for more than 255 seconds.
2019-04-29 16:27:49,903 - discord.gateway - WARNING - Heartbeat blocked for more than 260 seconds.
2019-04-29 16:27:54,908 - discord.gateway - WARNING - Heartbeat blocked for more than 265 seconds.
2019-04-29 16:27:56,129 - discord.gateway - INFO - Websocket closed with 1000 (), cannot reconnect.
2019-04-29 16:27:56,135 - discord.client - ERROR - Attempting a reconnect in 0.57s
Traceback (most recent call last):
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\discord\gateway.py", line 464, in poll_event
    msg = await self.recv()
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\websockets\protocol.py", line 350, in recv
    yield from self.ensure_open()
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\websockets\protocol.py", line 501, in ensure_open
    self.close_code, self.close_reason) from self.transfer_data_exc
websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1000 (OK), no reason

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\discord\client.py", line 431, in connect
    await self._connect()
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\discord\client.py", line 395, in _connect
    await self.ws.poll_event()
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\discord\gateway.py", line 472, in poll_event
    raise ConnectionClosed(exc, shard_id=self.shard_id) from exc
discord.errors.ConnectionClosed: WebSocket connection is closed: code = 1000 (OK), no reason
2019-04-29 16:27:57,050 - discord.gateway - INFO - Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
2019-04-29 16:27:57,059 - discord.gateway - INFO - Shard ID None has sent the IDENTIFY payload.
2019-04-29 16:27:57,217 - discord.gateway - INFO - Shard ID None has connected to Gateway: gateway-prd-main-n3zg, discord-sessions-prd-1-19 (Session ID: 630b40078ec2c6e0dee6c791b823ffec).
2019-04-29 16:28:12,635 - db_handler - INFO - Init DB connection
2019-04-29 16:28:17,632 - db_handler - INFO - {'ally_code': 376764962} found for 143651954919342080
2019-04-29 16:28:21,358 - swgoh_handler - INFO - Response 200 OK
2019-04-29 16:28:37,377 - discord.gateway - WARNING - Shard ID None has stopped responding to the gateway. Closing and restarting.
2019-04-29 16:28:53,129 - db_handler - INFO - Init DB connection
2019-04-29 16:28:59,827 - db_handler - INFO - {'ally_code': 376764962} found for 143651954919342080
2019-04-29 16:29:03,611 - swgoh_handler - INFO - Response 200 OK
2019-04-29 16:29:52,628 - db_handler - INFO - Init DB connection
2019-04-29 16:29:57,301 - db_handler - INFO - {'ally_code': 376764962} found for 143651954919342080
2019-04-29 16:30:00,703 - swgoh_handler - INFO - Response 200 OK
2019-04-30 15:42:22,045 - discord.client - WARNING - PyNaCl is not installed, voice will NOT be supported
2019-04-30 15:42:22,102 - db_handler - INFO - Init DB connection
2019-04-30 15:42:22,189 - db_handler - INFO - Init DB connection
2019-04-30 15:42:22,835 - db_handler - INFO - Init DB connection
2019-04-30 15:42:22,877 - discord.client - INFO - logging in using static token
2019-04-30 15:42:25,006 - discord.gateway - INFO - Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
2019-04-30 15:42:25,009 - discord.gateway - INFO - Shard ID None has sent the IDENTIFY payload.
2019-04-30 15:42:25,681 - discord.gateway - INFO - Shard ID None has connected to Gateway: gateway-prd-main-qcsh, discord-sessions-prd-1-6 (Session ID: 7d6fa7b8c4d59f75549f1bcb60e21ab5).
2019-04-30 15:45:50,859 - db_handler - INFO - User Intrapido#1503 added to the MongoDB
2019-04-30 15:48:56,338 - db_handler - INFO - Init DB connection
2019-04-30 15:49:53,997 - db_handler - INFO - User MonitQ#7059 added to the MongoDB
2019-04-30 15:50:53,397 - db_handler - INFO - {'ally_code': 567793738} found for 396358001646108691
2019-04-30 15:50:55,362 - swgoh_handler - INFO - Response 200 OK
2019-04-30 15:53:49,876 - discord.client - WARNING - PyNaCl is not installed, voice will NOT be supported
2019-04-30 15:53:49,878 - db_handler - INFO - Init DB connection
2019-04-30 15:53:49,886 - db_handler - INFO - Init DB connection
2019-04-30 15:53:49,986 - db_handler - INFO - Init DB connection
2019-04-30 15:53:49,991 - discord.client - INFO - logging in using static token
2019-04-30 15:53:51,444 - discord.gateway - INFO - Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
2019-04-30 15:53:51,459 - discord.gateway - INFO - Shard ID None has sent the IDENTIFY payload.
2019-04-30 15:53:51,693 - discord.gateway - INFO - Shard ID None has connected to Gateway: gateway-prd-main-bvj9, discord-sessions-prd-1-24 (Session ID: 1b5b92f36a54b55763956c579be6231b).
2019-04-30 15:54:20,065 - __main__ - ERROR - cndCheckUser cannot be unloaded. [Extension 'cndCheckUser' has not been loaded.]
Traceback (most recent call last):
  File "f:\_DEV\Discord\SnakeBot\__main__.py", line 64, in unload
    bot.unload_extension(extension)
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\discord\ext\commands\bot.py", line 650, in unload_extension
    raise errors.ExtensionNotLoaded(name)
discord.ext.commands.errors.ExtensionNotLoaded: Extension 'cndCheckUser' has not been loaded.
2019-04-30 15:54:37,724 - __main__ - ERROR - CkeckUser cannot be unloaded. [Extension 'CkeckUser' has not been loaded.]
Traceback (most recent call last):
  File "f:\_DEV\Discord\SnakeBot\__main__.py", line 64, in unload
    bot.unload_extension(extension)
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\discord\ext\commands\bot.py", line 650, in unload_extension
    raise errors.ExtensionNotLoaded(name)
discord.ext.commands.errors.ExtensionNotLoaded: Extension 'CkeckUser' has not been loaded.
2019-04-30 16:00:37,475 - db_handler - INFO - Init DB connection
2019-04-30 16:00:59,340 - db_handler - INFO - {'ally_code': 567793738} found for 396358001646108691
2019-04-30 16:01:00,212 - swgoh_handler - INFO - Response 200 OK
2019-04-30 16:03:26,497 - discord.client - WARNING - PyNaCl is not installed, voice will NOT be supported
2019-04-30 16:03:26,500 - db_handler - INFO - Init DB connection
2019-04-30 16:03:26,508 - db_handler - INFO - Init DB connection
2019-04-30 16:03:26,637 - db_handler - INFO - Init DB connection
2019-04-30 16:03:26,642 - discord.client - INFO - logging in using static token
2019-04-30 16:03:28,211 - discord.gateway - INFO - Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
2019-04-30 16:03:28,216 - discord.gateway - INFO - Shard ID None has sent the IDENTIFY payload.
2019-04-30 16:03:28,514 - discord.gateway - INFO - Shard ID None has connected to Gateway: gateway-prd-main-qg21, discord-sessions-prd-1-28 (Session ID: 375e6b160b1ade2c099acf9ead4dfd50).
2019-04-30 16:03:47,537 - db_handler - INFO - {'ally_code': 567793738} found for 396358001646108691
2019-04-30 16:03:48,687 - swgoh_handler - INFO - Response 200 OK
2019-04-30 16:05:00,893 - discord.client - WARNING - PyNaCl is not installed, voice will NOT be supported
2019-04-30 16:05:00,899 - db_handler - INFO - Init DB connection
2019-04-30 16:05:00,915 - db_handler - INFO - Init DB connection
2019-04-30 16:05:01,113 - db_handler - INFO - Init DB connection
2019-04-30 16:05:01,131 - discord.client - INFO - logging in using static token
2019-04-30 16:05:02,771 - discord.gateway - INFO - Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
2019-04-30 16:05:02,783 - discord.gateway - INFO - Shard ID None has sent the IDENTIFY payload.
2019-04-30 16:05:03,048 - discord.gateway - INFO - Shard ID None has connected to Gateway: gateway-prd-main-fgf7, discord-sessions-prd-1-5 (Session ID: 92231555c36d60a6029462f75120e55d).
2019-04-30 16:05:28,455 - db_handler - INFO - {'ally_code': 567793738} found for 396358001646108691
2019-04-30 16:05:29,769 - swgoh_handler - INFO - Response 200 OK
2019-04-30 16:05:49,034 - discord.gateway - WARNING - Heartbeat blocked for more than 5 seconds.
2019-04-30 16:05:54,039 - discord.gateway - WARNING - Heartbeat blocked for more than 10 seconds.
2019-04-30 16:05:59,043 - discord.gateway - WARNING - Heartbeat blocked for more than 15 seconds.
2019-04-30 16:06:04,051 - discord.gateway - WARNING - Heartbeat blocked for more than 20 seconds.
2019-04-30 16:06:09,055 - discord.gateway - WARNING - Heartbeat blocked for more than 25 seconds.
2019-04-30 16:06:14,063 - discord.gateway - WARNING - Heartbeat blocked for more than 30 seconds.
2019-04-30 16:06:19,070 - discord.gateway - WARNING - Heartbeat blocked for more than 35 seconds.
2019-04-30 16:06:24,079 - discord.gateway - WARNING - Heartbeat blocked for more than 40 seconds.
2019-04-30 16:06:29,087 - discord.gateway - WARNING - Heartbeat blocked for more than 45 seconds.
2019-04-30 16:06:34,090 - discord.gateway - WARNING - Heartbeat blocked for more than 50 seconds.
2019-04-30 16:06:39,092 - discord.gateway - WARNING - Heartbeat blocked for more than 55 seconds.
2019-04-30 16:06:44,099 - discord.gateway - WARNING - Heartbeat blocked for more than 60 seconds.
2019-04-30 16:06:49,106 - discord.gateway - WARNING - Heartbeat blocked for more than 65 seconds.
2019-04-30 16:06:54,108 - discord.gateway - WARNING - Heartbeat blocked for more than 70 seconds.
2019-04-30 16:06:59,111 - discord.gateway - WARNING - Heartbeat blocked for more than 75 seconds.
2019-04-30 16:07:04,115 - discord.gateway - WARNING - Heartbeat blocked for more than 80 seconds.
2019-04-30 16:07:09,122 - discord.gateway - WARNING - Heartbeat blocked for more than 85 seconds.
2019-04-30 16:07:14,129 - discord.gateway - WARNING - Heartbeat blocked for more than 90 seconds.
2019-04-30 16:07:19,131 - discord.gateway - WARNING - Heartbeat blocked for more than 95 seconds.
2019-04-30 16:07:24,139 - discord.gateway - WARNING - Heartbeat blocked for more than 100 seconds.
2019-04-30 16:07:29,149 - discord.gateway - WARNING - Heartbeat blocked for more than 105 seconds.
2019-04-30 16:07:34,169 - discord.gateway - WARNING - Heartbeat blocked for more than 110 seconds.
2019-04-30 16:07:39,172 - discord.gateway - WARNING - Heartbeat blocked for more than 115 seconds.
2019-04-30 16:07:44,175 - discord.gateway - WARNING - Heartbeat blocked for more than 120 seconds.
2019-04-30 16:07:49,182 - discord.gateway - WARNING - Heartbeat blocked for more than 125 seconds.
2019-04-30 16:07:54,184 - discord.gateway - WARNING - Heartbeat blocked for more than 130 seconds.
2019-04-30 16:07:59,191 - discord.gateway - WARNING - Heartbeat blocked for more than 135 seconds.
2019-04-30 16:08:04,198 - discord.gateway - WARNING - Heartbeat blocked for more than 140 seconds.
2019-04-30 16:08:09,204 - discord.gateway - WARNING - Heartbeat blocked for more than 145 seconds.
2019-04-30 16:08:14,208 - discord.gateway - WARNING - Heartbeat blocked for more than 150 seconds.
2019-04-30 16:08:19,217 - discord.gateway - WARNING - Heartbeat blocked for more than 155 seconds.
2019-04-30 16:08:24,228 - discord.gateway - WARNING - Heartbeat blocked for more than 160 seconds.
2019-04-30 16:08:29,239 - discord.gateway - WARNING - Heartbeat blocked for more than 165 seconds.
2019-04-30 16:08:34,242 - discord.gateway - WARNING - Heartbeat blocked for more than 170 seconds.
2019-04-30 16:08:39,249 - discord.gateway - WARNING - Heartbeat blocked for more than 175 seconds.
2019-04-30 16:08:44,256 - discord.gateway - WARNING - Heartbeat blocked for more than 180 seconds.
2019-04-30 16:08:49,263 - discord.gateway - WARNING - Heartbeat blocked for more than 185 seconds.
2019-04-30 16:08:54,272 - discord.gateway - WARNING - Heartbeat blocked for more than 190 seconds.
2019-04-30 16:08:59,281 - discord.gateway - WARNING - Heartbeat blocked for more than 195 seconds.
2019-04-30 16:09:04,285 - discord.gateway - WARNING - Heartbeat blocked for more than 200 seconds.
2019-04-30 16:09:09,289 - discord.gateway - WARNING - Heartbeat blocked for more than 205 seconds.
2019-04-30 16:09:14,298 - discord.gateway - WARNING - Heartbeat blocked for more than 210 seconds.
2019-04-30 16:09:19,308 - discord.gateway - WARNING - Heartbeat blocked for more than 215 seconds.
2019-04-30 16:09:24,313 - discord.gateway - WARNING - Heartbeat blocked for more than 220 seconds.
2019-04-30 16:09:29,321 - discord.gateway - WARNING - Heartbeat blocked for more than 225 seconds.
2019-04-30 16:09:34,329 - discord.gateway - WARNING - Heartbeat blocked for more than 230 seconds.
2019-04-30 16:13:50,568 - discord.client - WARNING - PyNaCl is not installed, voice will NOT be supported
2019-04-30 16:13:50,573 - db_handler - INFO - Init DB connection
2019-04-30 16:13:50,588 - db_handler - INFO - Init DB connection
2019-04-30 16:13:50,777 - db_handler - INFO - Init DB connection
2019-04-30 16:13:50,792 - discord.client - INFO - logging in using static token
2019-04-30 16:13:52,402 - discord.gateway - INFO - Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
2019-04-30 16:13:52,424 - discord.gateway - INFO - Shard ID None has sent the IDENTIFY payload.
2019-04-30 16:13:52,676 - discord.gateway - INFO - Shard ID None has connected to Gateway: gateway-prd-main-nrxf, discord-sessions-prd-1-16 (Session ID: a9a320f133819bf11b19ccd72d5049d9).
2019-04-30 16:14:10,199 - db_handler - INFO - {'ally_code': 567793738} found for 396358001646108691
2019-04-30 16:14:11,424 - swgoh_handler - INFO - Response 200 OK
2019-04-30 16:14:38,674 - discord.gateway - WARNING - Heartbeat blocked for more than 5 seconds.
2019-04-30 16:14:43,681 - discord.gateway - WARNING - Heartbeat blocked for more than 10 seconds.
2019-04-30 16:14:48,691 - discord.gateway - WARNING - Heartbeat blocked for more than 15 seconds.
2019-04-30 16:14:53,694 - discord.gateway - WARNING - Heartbeat blocked for more than 20 seconds.
2019-04-30 16:14:58,701 - discord.gateway - WARNING - Heartbeat blocked for more than 25 seconds.
2019-04-30 16:15:03,708 - discord.gateway - WARNING - Heartbeat blocked for more than 30 seconds.
2019-04-30 16:15:08,718 - discord.gateway - WARNING - Heartbeat blocked for more than 35 seconds.
2019-04-30 16:15:13,726 - discord.gateway - WARNING - Heartbeat blocked for more than 40 seconds.
2019-04-30 16:15:18,729 - discord.gateway - WARNING - Heartbeat blocked for more than 45 seconds.
2019-04-30 16:15:23,732 - discord.gateway - WARNING - Heartbeat blocked for more than 50 seconds.
2019-04-30 16:15:28,743 - discord.gateway - WARNING - Heartbeat blocked for more than 55 seconds.
2019-04-30 16:15:33,750 - discord.gateway - WARNING - Heartbeat blocked for more than 60 seconds.
2019-04-30 16:15:38,758 - discord.gateway - WARNING - Heartbeat blocked for more than 65 seconds.
2019-04-30 16:15:43,764 - discord.gateway - WARNING - Heartbeat blocked for more than 70 seconds.
2019-04-30 16:15:48,773 - discord.gateway - WARNING - Heartbeat blocked for more than 75 seconds.
2019-04-30 16:15:53,776 - discord.gateway - WARNING - Heartbeat blocked for more than 80 seconds.
2019-04-30 16:15:58,779 - discord.gateway - WARNING - Heartbeat blocked for more than 85 seconds.
2019-04-30 16:16:03,784 - discord.gateway - WARNING - Heartbeat blocked for more than 90 seconds.
2019-04-30 16:16:05,323 - discord.gateway - INFO - Websocket closed with 1000 (), cannot reconnect.
2019-04-30 16:16:05,328 - discord.client - ERROR - Attempting a reconnect in 1.56s
Traceback (most recent call last):
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\discord\gateway.py", line 464, in poll_event
    msg = await self.recv()
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\websockets\protocol.py", line 350, in recv
    yield from self.ensure_open()
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\websockets\protocol.py", line 512, in ensure_open
    self.close_code, self.close_reason) from self.transfer_data_exc
websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1000 (OK), no reason

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\discord\client.py", line 431, in connect
    await self._connect()
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\discord\client.py", line 395, in _connect
    await self.ws.poll_event()
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\discord\gateway.py", line 472, in poll_event
    raise ConnectionClosed(exc, shard_id=self.shard_id) from exc
discord.errors.ConnectionClosed: WebSocket connection is closed: code = 1000 (OK), no reason
2019-04-30 16:16:07,673 - discord.gateway - INFO - Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
2019-04-30 16:16:07,688 - discord.gateway - INFO - Shard ID None has sent the IDENTIFY payload.
2019-04-30 16:16:07,924 - discord.gateway - INFO - Shard ID None has connected to Gateway: gateway-prd-main-h5b1, discord-sessions-prd-1-21 (Session ID: 035c2c3f346e457b8281db34780d2cfa).
2019-04-30 16:26:53,600 - discord.client - WARNING - PyNaCl is not installed, voice will NOT be supported
2019-04-30 16:26:53,607 - db_handler - INFO - Init DB connection
2019-04-30 16:26:53,624 - db_handler - INFO - Init DB connection
2019-04-30 16:26:53,862 - db_handler - INFO - Init DB connection
2019-04-30 16:26:53,883 - discord.client - INFO - logging in using static token
2019-04-30 16:26:55,788 - discord.gateway - INFO - Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
2019-04-30 16:26:55,796 - discord.gateway - INFO - Shard ID None has sent the IDENTIFY payload.
2019-04-30 16:26:56,031 - discord.gateway - INFO - Shard ID None has connected to Gateway: gateway-prd-main-p4lk, discord-sessions-prd-1-23 (Session ID: 8cd5173ebe8bdfa37855347f20cd1565).
2019-04-30 16:27:04,983 - db_handler - INFO - {'ally_code': 567793738} found for 396358001646108691
2019-04-30 16:27:06,066 - swgoh_handler - INFO - Response 200 OK
2019-04-30 16:27:42,047 - discord.gateway - WARNING - Heartbeat blocked for more than 5 seconds.
2019-04-30 16:27:47,066 - discord.gateway - WARNING - Heartbeat blocked for more than 10 seconds.
2019-04-30 16:27:52,073 - discord.gateway - WARNING - Heartbeat blocked for more than 15 seconds.
2019-04-30 16:27:57,081 - discord.gateway - WARNING - Heartbeat blocked for more than 20 seconds.
2019-04-30 16:28:02,091 - discord.gateway - WARNING - Heartbeat blocked for more than 25 seconds.
2019-04-30 16:28:02,932 - db_handler - INFO - User update DONE for 396358001646108691 discordID
2019-04-30 16:28:07,094 - discord.gateway - WARNING - Heartbeat blocked for more than 30 seconds.
2019-04-30 16:28:12,099 - discord.gateway - WARNING - Heartbeat blocked for more than 35 seconds.
2019-04-30 16:28:17,102 - discord.gateway - WARNING - Heartbeat blocked for more than 40 seconds.
2019-04-30 16:28:22,106 - discord.gateway - WARNING - Heartbeat blocked for more than 45 seconds.
2019-04-30 16:28:27,111 - discord.gateway - WARNING - Heartbeat blocked for more than 50 seconds.
2019-04-30 16:28:32,117 - discord.gateway - WARNING - Heartbeat blocked for more than 55 seconds.
2019-04-30 16:28:37,121 - discord.gateway - WARNING - Heartbeat blocked for more than 60 seconds.
2019-04-30 16:28:42,128 - discord.gateway - WARNING - Heartbeat blocked for more than 65 seconds.
2019-04-30 16:28:47,135 - discord.gateway - WARNING - Heartbeat blocked for more than 70 seconds.
2019-04-30 16:28:52,139 - discord.gateway - WARNING - Heartbeat blocked for more than 75 seconds.
2019-04-30 16:28:57,143 - discord.gateway - WARNING - Heartbeat blocked for more than 80 seconds.
2019-04-30 16:29:02,148 - discord.gateway - WARNING - Heartbeat blocked for more than 85 seconds.
2019-04-30 16:29:07,150 - discord.gateway - WARNING - Heartbeat blocked for more than 90 seconds.
2019-04-30 16:29:12,156 - discord.gateway - WARNING - Heartbeat blocked for more than 95 seconds.
2019-04-30 16:29:17,162 - discord.gateway - WARNING - Heartbeat blocked for more than 100 seconds.
2019-04-30 16:29:22,170 - discord.gateway - WARNING - Heartbeat blocked for more than 105 seconds.
2019-04-30 16:29:27,182 - discord.gateway - WARNING - Heartbeat blocked for more than 110 seconds.
2019-04-30 16:29:32,190 - discord.gateway - WARNING - Heartbeat blocked for more than 115 seconds.
2019-04-30 16:29:34,108 - discord.gateway - INFO - Websocket closed with 1000 (), cannot reconnect.
2019-04-30 16:29:34,111 - discord.client - ERROR - Attempting a reconnect in 1.70s
Traceback (most recent call last):
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\discord\gateway.py", line 464, in poll_event
    msg = await self.recv()
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\websockets\protocol.py", line 350, in recv
    yield from self.ensure_open()
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\websockets\protocol.py", line 501, in ensure_open
    self.close_code, self.close_reason) from self.transfer_data_exc
websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1000 (OK), no reason

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\discord\client.py", line 431, in connect
    await self._connect()
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\discord\client.py", line 395, in _connect
    await self.ws.poll_event()
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\discord\gateway.py", line 472, in poll_event
    raise ConnectionClosed(exc, shard_id=self.shard_id) from exc
discord.errors.ConnectionClosed: WebSocket connection is closed: code = 1000 (OK), no reason
2019-04-30 16:29:36,575 - discord.gateway - INFO - Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
2019-04-30 16:29:36,594 - discord.gateway - INFO - Shard ID None has sent the IDENTIFY payload.
2019-04-30 16:29:37,225 - discord.gateway - INFO - Shard ID None has connected to Gateway: gateway-prd-main-8cw8, discord-sessions-prd-1-28 (Session ID: f5f31fed0670eae1c6f1dd7f31939035).
2019-04-30 16:29:44,191 - __main__ - ERROR - cndCheckuser cannot be unloaded. [Extension 'cndCheckuser' has not been loaded.]
Traceback (most recent call last):
  File "f:\_DEV\Discord\SnakeBot\__main__.py", line 64, in unload
    bot.unload_extension(extension)
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\discord\ext\commands\bot.py", line 650, in unload_extension
    raise errors.ExtensionNotLoaded(name)
discord.ext.commands.errors.ExtensionNotLoaded: Extension 'cndCheckuser' has not been loaded.
2019-04-30 16:29:56,354 - __main__ - ERROR - cmdCheckuser cannot be unloaded. [Extension 'cmdCheckuser' has not been loaded.]
Traceback (most recent call last):
  File "f:\_DEV\Discord\SnakeBot\__main__.py", line 64, in unload
    bot.unload_extension(extension)
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\discord\ext\commands\bot.py", line 650, in unload_extension
    raise errors.ExtensionNotLoaded(name)
discord.ext.commands.errors.ExtensionNotLoaded: Extension 'cmdCheckuser' has not been loaded.
2019-04-30 16:30:15,358 - discord.gateway - WARNING - Shard ID None has stopped responding to the gateway. Closing and restarting.
2019-04-30 16:36:10,300 - db_handler - INFO - Init DB connection
2019-04-30 16:36:23,475 - db_handler - INFO - {'ally_code': 567793738} found for 396358001646108691
2019-04-30 16:36:24,463 - swgoh_handler - INFO - Response 200 OK
2019-04-30 16:37:25,739 - db_handler - INFO - Init DB connection
2019-04-30 16:37:37,700 - db_handler - INFO - {'ally_code': 471941296} found for 269074011185610762
2019-04-30 16:37:39,419 - swgoh_handler - INFO - Response 200 OK
2019-04-30 16:37:39,481 - db_handler - INFO - User update DONE for 269074011185610762 discordID
2019-04-30 16:37:53,521 - db_handler - INFO - {'ally_code': 376764962} found for 143651954919342080
2019-04-30 16:37:55,153 - swgoh_handler - INFO - Response 200 OK
2019-04-30 16:37:55,207 - db_handler - INFO - User update DONE for 143651954919342080 discordID
2019-05-01 19:01:59,954 - discord.client - WARNING - PyNaCl is not installed, voice will NOT be supported
2019-05-01 19:01:59,984 - db_handler - INFO - Init DB connection
2019-05-01 19:02:00,027 - db_handler - INFO - Init DB connection
2019-05-01 19:02:00,546 - db_handler - INFO - Init DB connection
2019-05-01 19:02:00,561 - discord.client - INFO - logging in using static token
2019-05-01 19:02:01,911 - discord.gateway - INFO - Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
2019-05-01 19:02:01,915 - discord.gateway - INFO - Shard ID None has sent the IDENTIFY payload.
2019-05-01 19:02:02,762 - discord.gateway - INFO - Shard ID None has connected to Gateway: gateway-prd-main-01vm, discord-sessions-prd-1-23 (Session ID: 355cabd2f5a3c98ec7e4c91cfeb943f8).
2019-05-01 19:02:20,886 - db_handler - INFO - {'ally_code': 376764962} found for 143651954919342080
2019-05-01 19:02:22,242 - swgoh_handler - INFO - Response 200 OK
2019-05-01 19:02:22,276 - db_handler - ERROR - User update is FAILED
Traceback (most recent call last):
  File "f:\_DEV\Discord\SnakeBot\db_handler.py", line 115, in user_update
    self.action2 = self.col_discord.update_one(self.query2, self.new_value)
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\pymongo\collection.py", line 1002, in update_one
    session=session),
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\pymongo\collection.py", line 858, in _update_retryable
    _update, session)
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\pymongo\mongo_client.py", line 1280, in _retryable_write
    return self._retry_with_session(retryable, func, s, None)
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\pymongo\mongo_client.py", line 1233, in _retry_with_session
    return func(session, sock_info, retryable)
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\pymongo\collection.py", line 854, in _update
    retryable_write=retryable_write)
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\pymongo\collection.py", line 824, in _update
    retryable_write=retryable_write).copy()
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\pymongo\pool.py", line 589, in command
    self._raise_connection_failure(error)
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\pymongo\pool.py", line 750, in _raise_connection_failure
    raise error
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\pymongo\pool.py", line 584, in command
    user_fields=user_fields)
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\pymongo\network.py", line 121, in command
    codec_options, ctx=compression_ctx)
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\pymongo\message.py", line 678, in _op_msg
    flags, command, identifier, docs, check_keys, opts)
bson.errors.InvalidDocument: documents must have only string keys, key was datetime.date(2019, 5, 1)
2019-05-01 19:04:36,467 - discord.client - WARNING - PyNaCl is not installed, voice will NOT be supported
2019-05-01 19:04:36,469 - db_handler - INFO - Init DB connection
2019-05-01 19:04:36,478 - db_handler - INFO - Init DB connection
2019-05-01 19:04:36,597 - db_handler - INFO - Init DB connection
2019-05-01 19:04:36,602 - discord.client - INFO - logging in using static token
2019-05-01 19:04:37,709 - discord.gateway - INFO - Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
2019-05-01 19:04:37,713 - discord.gateway - INFO - Shard ID None has sent the IDENTIFY payload.
2019-05-01 19:04:37,902 - discord.gateway - INFO - Shard ID None has connected to Gateway: gateway-prd-main-9ln1, discord-sessions-prd-1-11 (Session ID: da97ec96096c3b31dbbe70974589b539).
2019-05-01 19:06:22,192 - db_handler - INFO - {'ally_code': 376764962} found for 143651954919342080
2019-05-01 19:06:22,956 - swgoh_handler - INFO - Response 200 OK
2019-05-01 19:06:22,991 - db_handler - INFO - User update DONE for 143651954919342080 discordID
2019-05-01 19:17:32,914 - discord.client - WARNING - PyNaCl is not installed, voice will NOT be supported
2019-05-01 19:17:32,917 - db_handler - INFO - Init DB connection
2019-05-01 19:17:32,925 - db_handler - INFO - Init DB connection
2019-05-01 19:17:33,036 - db_handler - INFO - Init DB connection
2019-05-01 19:17:33,041 - discord.client - INFO - logging in using static token
2019-05-01 19:17:34,258 - discord.gateway - INFO - Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
2019-05-01 19:17:34,266 - discord.gateway - INFO - Shard ID None has sent the IDENTIFY payload.
2019-05-01 19:17:35,021 - discord.gateway - INFO - Shard ID None has connected to Gateway: gateway-prd-main-fgf7, discord-sessions-prd-1-18 (Session ID: 2be44157e0d9e020958de0d00144bf78).
2019-05-01 19:17:51,094 - db_handler - INFO - {'ally_code': 376764962} found for 143651954919342080
2019-05-01 19:17:52,492 - swgoh_handler - INFO - Response 200 OK
2019-05-01 19:17:52,540 - db_handler - INFO - User update DONE with new 2019-05-01 progress data
2019-05-01 19:24:07,087 - discord.gateway - INFO - Websocket closed with 1006 (), attempting a reconnect.
2019-05-01 19:24:07,088 - discord.client - INFO - Got a request to RESUME the websocket.
2019-05-01 19:24:07,097 - discord.client - ERROR - Attempting a reconnect in 1.17s
Traceback (most recent call last):
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\aiohttp\connector.py", line 955, in _create_direct_connection
    traces=traces), loop=self._loop)
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\aiohttp\connector.py", line 825, in _resolve_host
    self._resolver.resolve(host, port, family=self._family)
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\aiohttp\resolver.py", line 30, in resolve
    host, port, type=socket.SOCK_STREAM, family=family)
  File "d:\python3.6-64\Lib\concurrent\futures\thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "d:\python3.6-64\Lib\socket.py", line 743, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\discord\client.py", line 431, in connect
    await self._connect()
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\discord\client.py", line 401, in _connect
    self.ws = await asyncio.wait_for(coro, timeout=180.0, loop=self.loop)
  File "d:\python3.6-64\Lib\asyncio\tasks.py", line 358, in wait_for
    return fut.result()
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\discord\gateway.py", line 219, in from_client
    gateway = await client.http.get_gateway()
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\discord\http.py", line 786, in get_gateway
    data = await self.request(Route('GET', '/gateway'))
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\discord\http.py", line 158, in request
    async with self.__session.request(method, url, **kwargs) as r:
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\aiohttp\client.py", line 1005, in __aenter__
    self._resp = await self._coro
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\aiohttp\client.py", line 476, in _request
    timeout=real_timeout
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\aiohttp\connector.py", line 522, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\aiohttp\connector.py", line 854, in _create_connection
    req, traces, timeout)
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\aiohttp\connector.py", line 959, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host discordapp.com:443 ssl:None [getaddrinfo failed]
2019-05-01 19:24:08,318 - discord.client - ERROR - Attempting a reconnect in 1.46s
Traceback (most recent call last):
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\aiohttp\connector.py", line 955, in _create_direct_connection
    traces=traces), loop=self._loop)
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\aiohttp\connector.py", line 825, in _resolve_host
    self._resolver.resolve(host, port, family=self._family)
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\aiohttp\resolver.py", line 30, in resolve
    host, port, type=socket.SOCK_STREAM, family=family)
  File "d:\python3.6-64\Lib\concurrent\futures\thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "d:\python3.6-64\Lib\socket.py", line 743, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\discord\client.py", line 431, in connect
    await self._connect()
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\discord\client.py", line 392, in _connect
    self.ws = await asyncio.wait_for(coro, timeout=180.0, loop=self.loop)
  File "d:\python3.6-64\Lib\asyncio\tasks.py", line 358, in wait_for
    return fut.result()
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\discord\gateway.py", line 219, in from_client
    gateway = await client.http.get_gateway()
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\discord\http.py", line 786, in get_gateway
    data = await self.request(Route('GET', '/gateway'))
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\discord\http.py", line 158, in request
    async with self.__session.request(method, url, **kwargs) as r:
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\aiohttp\client.py", line 1005, in __aenter__
    self._resp = await self._coro
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\aiohttp\client.py", line 476, in _request
    timeout=real_timeout
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\aiohttp\connector.py", line 522, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\aiohttp\connector.py", line 854, in _create_connection
    req, traces, timeout)
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\aiohttp\connector.py", line 959, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host discordapp.com:443 ssl:None [getaddrinfo failed]
2019-05-01 19:24:09,800 - discord.client - ERROR - Attempting a reconnect in 4.25s
Traceback (most recent call last):
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\aiohttp\connector.py", line 955, in _create_direct_connection
    traces=traces), loop=self._loop)
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\aiohttp\connector.py", line 825, in _resolve_host
    self._resolver.resolve(host, port, family=self._family)
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\aiohttp\resolver.py", line 30, in resolve
    host, port, type=socket.SOCK_STREAM, family=family)
  File "d:\python3.6-64\Lib\concurrent\futures\thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "d:\python3.6-64\Lib\socket.py", line 743, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\discord\client.py", line 431, in connect
    await self._connect()
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\discord\client.py", line 392, in _connect
    self.ws = await asyncio.wait_for(coro, timeout=180.0, loop=self.loop)
  File "d:\python3.6-64\Lib\asyncio\tasks.py", line 358, in wait_for
    return fut.result()
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\discord\gateway.py", line 219, in from_client
    gateway = await client.http.get_gateway()
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\discord\http.py", line 786, in get_gateway
    data = await self.request(Route('GET', '/gateway'))
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\discord\http.py", line 158, in request
    async with self.__session.request(method, url, **kwargs) as r:
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\aiohttp\client.py", line 1005, in __aenter__
    self._resp = await self._coro
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\aiohttp\client.py", line 476, in _request
    timeout=real_timeout
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\aiohttp\connector.py", line 522, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\aiohttp\connector.py", line 854, in _create_connection
    req, traces, timeout)
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\aiohttp\connector.py", line 959, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host discordapp.com:443 ssl:None [getaddrinfo failed]
2019-05-01 19:24:26,080 - discord.client - ERROR - Attempting a reconnect in 3.31s
Traceback (most recent call last):
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\aiohttp\connector.py", line 955, in _create_direct_connection
    traces=traces), loop=self._loop)
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\aiohttp\connector.py", line 825, in _resolve_host
    self._resolver.resolve(host, port, family=self._family)
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\aiohttp\resolver.py", line 30, in resolve
    host, port, type=socket.SOCK_STREAM, family=family)
  File "d:\python3.6-64\Lib\concurrent\futures\thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "d:\python3.6-64\Lib\socket.py", line 743, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\discord\client.py", line 431, in connect
    await self._connect()
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\discord\client.py", line 392, in _connect
    self.ws = await asyncio.wait_for(coro, timeout=180.0, loop=self.loop)
  File "d:\python3.6-64\Lib\asyncio\tasks.py", line 358, in wait_for
    return fut.result()
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\discord\gateway.py", line 219, in from_client
    gateway = await client.http.get_gateway()
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\discord\http.py", line 786, in get_gateway
    data = await self.request(Route('GET', '/gateway'))
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\discord\http.py", line 158, in request
    async with self.__session.request(method, url, **kwargs) as r:
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\aiohttp\client.py", line 1005, in __aenter__
    self._resp = await self._coro
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\aiohttp\client.py", line 476, in _request
    timeout=real_timeout
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\aiohttp\connector.py", line 522, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\aiohttp\connector.py", line 854, in _create_connection
    req, traces, timeout)
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\aiohttp\connector.py", line 959, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host discordapp.com:443 ssl:None [getaddrinfo failed]
2019-05-01 19:24:26,807 - discord.gateway - WARNING - Shard ID None has stopped responding to the gateway. Closing and restarting.
2019-05-01 19:24:29,426 - discord.client - ERROR - Attempting a reconnect in 13.01s
Traceback (most recent call last):
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\aiohttp\connector.py", line 955, in _create_direct_connection
    traces=traces), loop=self._loop)
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\aiohttp\connector.py", line 825, in _resolve_host
    self._resolver.resolve(host, port, family=self._family)
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\aiohttp\resolver.py", line 30, in resolve
    host, port, type=socket.SOCK_STREAM, family=family)
  File "d:\python3.6-64\Lib\concurrent\futures\thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "d:\python3.6-64\Lib\socket.py", line 743, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\discord\client.py", line 431, in connect
    await self._connect()
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\discord\client.py", line 392, in _connect
    self.ws = await asyncio.wait_for(coro, timeout=180.0, loop=self.loop)
  File "d:\python3.6-64\Lib\asyncio\tasks.py", line 358, in wait_for
    return fut.result()
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\discord\gateway.py", line 219, in from_client
    gateway = await client.http.get_gateway()
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\discord\http.py", line 786, in get_gateway
    data = await self.request(Route('GET', '/gateway'))
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\discord\http.py", line 158, in request
    async with self.__session.request(method, url, **kwargs) as r:
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\aiohttp\client.py", line 1005, in __aenter__
    self._resp = await self._coro
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\aiohttp\client.py", line 476, in _request
    timeout=real_timeout
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\aiohttp\connector.py", line 522, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\aiohttp\connector.py", line 854, in _create_connection
    req, traces, timeout)
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\aiohttp\connector.py", line 959, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host discordapp.com:443 ssl:None [getaddrinfo failed]
2019-05-01 19:24:42,449 - discord.client - ERROR - Attempting a reconnect in 24.24s
Traceback (most recent call last):
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\aiohttp\connector.py", line 955, in _create_direct_connection
    traces=traces), loop=self._loop)
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\aiohttp\connector.py", line 825, in _resolve_host
    self._resolver.resolve(host, port, family=self._family)
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\aiohttp\resolver.py", line 30, in resolve
    host, port, type=socket.SOCK_STREAM, family=family)
  File "d:\python3.6-64\Lib\concurrent\futures\thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "d:\python3.6-64\Lib\socket.py", line 743, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\discord\client.py", line 431, in connect
    await self._connect()
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\discord\client.py", line 392, in _connect
    self.ws = await asyncio.wait_for(coro, timeout=180.0, loop=self.loop)
  File "d:\python3.6-64\Lib\asyncio\tasks.py", line 358, in wait_for
    return fut.result()
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\discord\gateway.py", line 219, in from_client
    gateway = await client.http.get_gateway()
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\discord\http.py", line 786, in get_gateway
    data = await self.request(Route('GET', '/gateway'))
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\discord\http.py", line 158, in request
    async with self.__session.request(method, url, **kwargs) as r:
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\aiohttp\client.py", line 1005, in __aenter__
    self._resp = await self._coro
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\aiohttp\client.py", line 476, in _request
    timeout=real_timeout
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\aiohttp\connector.py", line 522, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\aiohttp\connector.py", line 854, in _create_connection
    req, traces, timeout)
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\aiohttp\connector.py", line 959, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host discordapp.com:443 ssl:None [getaddrinfo failed]
2019-05-01 19:25:06,701 - discord.client - ERROR - Attempting a reconnect in 77.37s
Traceback (most recent call last):
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\aiohttp\connector.py", line 955, in _create_direct_connection
    traces=traces), loop=self._loop)
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\aiohttp\connector.py", line 825, in _resolve_host
    self._resolver.resolve(host, port, family=self._family)
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\aiohttp\resolver.py", line 30, in resolve
    host, port, type=socket.SOCK_STREAM, family=family)
  File "d:\python3.6-64\Lib\concurrent\futures\thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "d:\python3.6-64\Lib\socket.py", line 743, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\discord\client.py", line 431, in connect
    await self._connect()
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\discord\client.py", line 392, in _connect
    self.ws = await asyncio.wait_for(coro, timeout=180.0, loop=self.loop)
  File "d:\python3.6-64\Lib\asyncio\tasks.py", line 358, in wait_for
    return fut.result()
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\discord\gateway.py", line 219, in from_client
    gateway = await client.http.get_gateway()
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\discord\http.py", line 786, in get_gateway
    data = await self.request(Route('GET', '/gateway'))
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\discord\http.py", line 158, in request
    async with self.__session.request(method, url, **kwargs) as r:
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\aiohttp\client.py", line 1005, in __aenter__
    self._resp = await self._coro
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\aiohttp\client.py", line 476, in _request
    timeout=real_timeout
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\aiohttp\connector.py", line 522, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\aiohttp\connector.py", line 854, in _create_connection
    req, traces, timeout)
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\aiohttp\connector.py", line 959, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host discordapp.com:443 ssl:None [getaddrinfo failed]
2019-05-01 19:26:24,601 - discord.gateway - INFO - Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
2019-05-01 19:26:24,605 - discord.gateway - INFO - Shard ID None has sent the IDENTIFY payload.
2019-05-01 19:26:25,075 - discord.gateway - INFO - Shard ID None has connected to Gateway: gateway-prd-main-rwdh, discord-sessions-prd-1-14 (Session ID: 1beec07d4337ad5f1d828d5a4e13fd1c).
2019-05-01 19:31:21,948 - db_handler - INFO - {'ally_code': 567793738} found for 396358001646108691
2019-05-01 19:31:23,405 - swgoh_handler - INFO - Response 200 OK
2019-05-01 19:31:23,442 - db_handler - INFO - User update DONE with new 2019-05-01 progress data
2019-05-01 19:31:32,118 - db_handler - INFO - {'ally_code': 471941296} found for 269074011185610762
2019-05-01 19:31:33,500 - swgoh_handler - INFO - Response 200 OK
2019-05-01 19:31:33,558 - db_handler - INFO - User update DONE with new 2019-04-30 progress data
2019-05-01 19:33:40,082 - db_handler - INFO - {'ally_code': 567793738} found for 396358001646108691
2019-05-01 19:33:40,870 - swgoh_handler - INFO - Response 200 OK
2019-05-01 19:33:40,914 - db_handler - INFO - User update DONE for 396358001646108691 discordID
2019-05-01 19:33:49,020 - db_handler - INFO - {'ally_code': 471941296} found for 269074011185610762
2019-05-01 19:33:49,749 - swgoh_handler - INFO - Response 200 OK
2019-05-01 19:33:49,793 - db_handler - INFO - User update DONE for 269074011185610762 discordID
2019-05-01 19:40:30,319 - discord.gateway - INFO - Websocket closed with 1006 (), attempting a reconnect.
2019-05-01 19:40:30,320 - discord.client - INFO - Got a request to RESUME the websocket.
2019-05-01 19:40:30,801 - discord.gateway - INFO - Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
2019-05-01 19:40:30,805 - discord.gateway - INFO - Shard ID None has sent the RESUME payload.
2019-05-01 19:40:30,938 - discord.gateway - INFO - Shard ID None has successfully RESUMED session 1beec07d4337ad5f1d828d5a4e13fd1c under trace gateway-prd-main-2sw1, discord-sessions-prd-1-14.
2019-05-01 19:41:32,146 - discord.gateway - WARNING - Shard ID None has stopped responding to the gateway. Closing and restarting.
2019-05-01 23:05:18,641 - discord.gateway - INFO - Websocket closed with 1006 (), attempting a reconnect.
2019-05-01 23:05:18,641 - discord.client - INFO - Got a request to RESUME the websocket.
2019-05-01 23:05:18,745 - discord.client - ERROR - Attempting a reconnect in 1.36s
Traceback (most recent call last):
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\aiohttp\connector.py", line 955, in _create_direct_connection
    traces=traces), loop=self._loop)
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\aiohttp\connector.py", line 825, in _resolve_host
    self._resolver.resolve(host, port, family=self._family)
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\aiohttp\resolver.py", line 30, in resolve
    host, port, type=socket.SOCK_STREAM, family=family)
  File "d:\python3.6-64\Lib\concurrent\futures\thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "d:\python3.6-64\Lib\socket.py", line 743, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\discord\client.py", line 431, in connect
    await self._connect()
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\discord\client.py", line 401, in _connect
    self.ws = await asyncio.wait_for(coro, timeout=180.0, loop=self.loop)
  File "d:\python3.6-64\Lib\asyncio\tasks.py", line 358, in wait_for
    return fut.result()
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\discord\gateway.py", line 219, in from_client
    gateway = await client.http.get_gateway()
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\discord\http.py", line 786, in get_gateway
    data = await self.request(Route('GET', '/gateway'))
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\discord\http.py", line 158, in request
    async with self.__session.request(method, url, **kwargs) as r:
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\aiohttp\client.py", line 1005, in __aenter__
    self._resp = await self._coro
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\aiohttp\client.py", line 476, in _request
    timeout=real_timeout
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\aiohttp\connector.py", line 522, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\aiohttp\connector.py", line 854, in _create_connection
    req, traces, timeout)
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\aiohttp\connector.py", line 959, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host discordapp.com:443 ssl:None [getaddrinfo failed]
2019-05-01 23:05:20,524 - discord.client - ERROR - Attempting a reconnect in 2.92s
Traceback (most recent call last):
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\aiohttp\connector.py", line 955, in _create_direct_connection
    traces=traces), loop=self._loop)
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\aiohttp\connector.py", line 825, in _resolve_host
    self._resolver.resolve(host, port, family=self._family)
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\aiohttp\resolver.py", line 30, in resolve
    host, port, type=socket.SOCK_STREAM, family=family)
  File "d:\python3.6-64\Lib\concurrent\futures\thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "d:\python3.6-64\Lib\socket.py", line 743, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\discord\client.py", line 431, in connect
    await self._connect()
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\discord\client.py", line 392, in _connect
    self.ws = await asyncio.wait_for(coro, timeout=180.0, loop=self.loop)
  File "d:\python3.6-64\Lib\asyncio\tasks.py", line 358, in wait_for
    return fut.result()
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\discord\gateway.py", line 219, in from_client
    gateway = await client.http.get_gateway()
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\discord\http.py", line 786, in get_gateway
    data = await self.request(Route('GET', '/gateway'))
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\discord\http.py", line 158, in request
    async with self.__session.request(method, url, **kwargs) as r:
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\aiohttp\client.py", line 1005, in __aenter__
    self._resp = await self._coro
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\aiohttp\client.py", line 476, in _request
    timeout=real_timeout
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\aiohttp\connector.py", line 522, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\aiohttp\connector.py", line 854, in _create_connection
    req, traces, timeout)
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\aiohttp\connector.py", line 959, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host discordapp.com:443 ssl:None [getaddrinfo failed]
2019-05-01 23:05:23,974 - discord.client - ERROR - Attempting a reconnect in 4.76s
Traceback (most recent call last):
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\aiohttp\connector.py", line 955, in _create_direct_connection
    traces=traces), loop=self._loop)
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\aiohttp\connector.py", line 825, in _resolve_host
    self._resolver.resolve(host, port, family=self._family)
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\aiohttp\resolver.py", line 30, in resolve
    host, port, type=socket.SOCK_STREAM, family=family)
  File "d:\python3.6-64\Lib\concurrent\futures\thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "d:\python3.6-64\Lib\socket.py", line 743, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\discord\client.py", line 431, in connect
    await self._connect()
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\discord\client.py", line 392, in _connect
    self.ws = await asyncio.wait_for(coro, timeout=180.0, loop=self.loop)
  File "d:\python3.6-64\Lib\asyncio\tasks.py", line 358, in wait_for
    return fut.result()
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\discord\gateway.py", line 219, in from_client
    gateway = await client.http.get_gateway()
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\discord\http.py", line 786, in get_gateway
    data = await self.request(Route('GET', '/gateway'))
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\discord\http.py", line 158, in request
    async with self.__session.request(method, url, **kwargs) as r:
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\aiohttp\client.py", line 1005, in __aenter__
    self._resp = await self._coro
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\aiohttp\client.py", line 476, in _request
    timeout=real_timeout
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\aiohttp\connector.py", line 522, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\aiohttp\connector.py", line 854, in _create_connection
    req, traces, timeout)
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\aiohttp\connector.py", line 959, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host discordapp.com:443 ssl:None [getaddrinfo failed]
2019-05-01 23:05:29,249 - discord.gateway - INFO - Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
2019-05-01 23:05:29,384 - discord.gateway - INFO - Shard ID None has sent the IDENTIFY payload.
2019-05-01 23:05:29,584 - discord.gateway - INFO - Shard ID None has connected to Gateway: gateway-prd-main-xsd1, discord-sessions-prd-1-20 (Session ID: 1c3138d02b4b49795878b0392d665396).
2019-05-02 07:51:28,815 - discord.gateway - INFO - Websocket closed with 1006 (), attempting a reconnect.
2019-05-02 07:51:28,815 - discord.client - INFO - Got a request to RESUME the websocket.
2019-05-02 07:51:29,166 - discord.client - ERROR - Attempting a reconnect in 0.75s
Traceback (most recent call last):
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\aiohttp\connector.py", line 955, in _create_direct_connection
    traces=traces), loop=self._loop)
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\aiohttp\connector.py", line 825, in _resolve_host
    self._resolver.resolve(host, port, family=self._family)
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\aiohttp\resolver.py", line 30, in resolve
    host, port, type=socket.SOCK_STREAM, family=family)
  File "d:\python3.6-64\Lib\concurrent\futures\thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "d:\python3.6-64\Lib\socket.py", line 743, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\discord\client.py", line 431, in connect
    await self._connect()
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\discord\client.py", line 401, in _connect
    self.ws = await asyncio.wait_for(coro, timeout=180.0, loop=self.loop)
  File "d:\python3.6-64\Lib\asyncio\tasks.py", line 358, in wait_for
    return fut.result()
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\discord\gateway.py", line 219, in from_client
    gateway = await client.http.get_gateway()
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\discord\http.py", line 786, in get_gateway
    data = await self.request(Route('GET', '/gateway'))
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\discord\http.py", line 158, in request
    async with self.__session.request(method, url, **kwargs) as r:
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\aiohttp\client.py", line 1005, in __aenter__
    self._resp = await self._coro
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\aiohttp\client.py", line 476, in _request
    timeout=real_timeout
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\aiohttp\connector.py", line 522, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\aiohttp\connector.py", line 854, in _create_connection
    req, traces, timeout)
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\aiohttp\connector.py", line 959, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host discordapp.com:443 ssl:None [getaddrinfo failed]
2019-05-02 07:51:31,490 - discord.gateway - WARNING - Shard ID None has stopped responding to the gateway. Closing and restarting.
2019-05-02 07:51:34,453 - discord.client - ERROR - Attempting a reconnect in 1.30s
Traceback (most recent call last):
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\aiohttp\connector.py", line 955, in _create_direct_connection
    traces=traces), loop=self._loop)
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\aiohttp\connector.py", line 825, in _resolve_host
    self._resolver.resolve(host, port, family=self._family)
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\aiohttp\resolver.py", line 30, in resolve
    host, port, type=socket.SOCK_STREAM, family=family)
  File "d:\python3.6-64\Lib\concurrent\futures\thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "d:\python3.6-64\Lib\socket.py", line 743, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\discord\client.py", line 431, in connect
    await self._connect()
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\discord\client.py", line 392, in _connect
    self.ws = await asyncio.wait_for(coro, timeout=180.0, loop=self.loop)
  File "d:\python3.6-64\Lib\asyncio\tasks.py", line 358, in wait_for
    return fut.result()
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\discord\gateway.py", line 219, in from_client
    gateway = await client.http.get_gateway()
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\discord\http.py", line 786, in get_gateway
    data = await self.request(Route('GET', '/gateway'))
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\discord\http.py", line 158, in request
    async with self.__session.request(method, url, **kwargs) as r:
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\aiohttp\client.py", line 1005, in __aenter__
    self._resp = await self._coro
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\aiohttp\client.py", line 476, in _request
    timeout=real_timeout
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\aiohttp\connector.py", line 522, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\aiohttp\connector.py", line 854, in _create_connection
    req, traces, timeout)
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\aiohttp\connector.py", line 959, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host discordapp.com:443 ssl:None [getaddrinfo failed]
2019-05-02 07:51:37,681 - discord.client - ERROR - Attempting a reconnect in 6.88s
Traceback (most recent call last):
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\discord\client.py", line 431, in connect
    await self._connect()
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\discord\client.py", line 392, in _connect
    self.ws = await asyncio.wait_for(coro, timeout=180.0, loop=self.loop)
  File "d:\python3.6-64\Lib\asyncio\tasks.py", line 358, in wait_for
    return fut.result()
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\discord\gateway.py", line 220, in from_client
    ws = await websockets.connect(gateway, loop=client.loop, klass=cls, compression=None)
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\websockets\py35\client.py", line 12, in __await_impl__
    transport, protocol = await self._creating_connection
  File "d:\python3.6-64\Lib\asyncio\base_events.py", line 733, in create_connection
    infos = f1.result()
  File "d:\python3.6-64\Lib\concurrent\futures\thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "d:\python3.6-64\Lib\socket.py", line 743, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed
2019-05-02 07:51:45,049 - discord.gateway - INFO - Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
2019-05-02 07:51:45,336 - discord.gateway - INFO - Shard ID None has sent the IDENTIFY payload.
2019-05-02 07:51:45,500 - discord.gateway - INFO - Shard ID None has connected to Gateway: gateway-prd-main-qcsh, discord-sessions-prd-1-26 (Session ID: e29a44cd26e6a29834cc789afe6e6e83).
2019-05-02 07:51:49,899 - discord.gateway - WARNING - Shard ID None has stopped responding to the gateway. Closing and restarting.
2019-05-02 10:13:48,382 - discord.client - WARNING - PyNaCl is not installed, voice will NOT be supported
2019-05-02 10:13:48,386 - db_handler - INFO - Init DB connection
2019-05-02 10:13:48,413 - db_handler - INFO - Init DB connection
2019-05-02 10:13:49,002 - db_handler - INFO - Init DB connection
2019-05-02 10:13:49,028 - discord.client - INFO - logging in using static token
2019-05-02 10:13:50,450 - discord.gateway - INFO - Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
2019-05-02 10:13:50,453 - discord.gateway - INFO - Shard ID None has sent the IDENTIFY payload.
2019-05-02 10:13:50,600 - discord.gateway - INFO - Shard ID None has connected to Gateway: gateway-prd-main-jg92, discord-sessions-prd-1-17 (Session ID: 85df427719f16f54d02897942e961e63).
2019-05-02 10:15:01,640 - db_handler - INFO - User newl#0773 added to the MongoDB
2019-05-02 10:15:14,263 - db_handler - INFO - {'ally_code': 999134554} found for 353891399550238721
2019-05-02 10:15:15,568 - swgoh_handler - INFO - Response 200 OK
2019-05-02 10:15:15,619 - db_handler - INFO - User update DONE for 353891399550238721 discordID
2019-05-02 11:09:48,688 - db_handler - INFO - {'ally_code': 376764962} found for 143651954919342080
2019-05-02 11:09:49,966 - swgoh_handler - INFO - Response 200 OK
2019-05-02 11:10:31,928 - db_handler - INFO - {'ally_code': 376764962} found for 143651954919342080
2019-05-02 11:10:32,603 - swgoh_handler - INFO - Response 200 OK
2019-05-02 11:26:13,451 - db_handler - INFO - {'ally_code': 376764962} found for 143651954919342080
2019-05-02 11:26:14,026 - swgoh_handler - INFO - Response 200 OK
2019-05-02 11:44:03,504 - db_handler - INFO - {'ally_code': 567793738} found for 396358001646108691
2019-05-02 11:44:04,855 - swgoh_handler - INFO - Response 200 OK
2019-05-02 11:44:13,426 - db_handler - INFO - {'ally_code': 471941296} found for 269074011185610762
2019-05-02 11:44:14,691 - swgoh_handler - INFO - Response 200 OK
2019-05-02 11:44:14,721 - db_handler - INFO - User update DONE with new 2019-05-01 progress data
2019-05-02 13:41:16,394 - discord.client - WARNING - PyNaCl is not installed, voice will NOT be supported
2019-05-02 13:41:16,399 - db_handler - INFO - Init DB connection
2019-05-02 13:41:16,472 - db_handler - INFO - Init DB connection
2019-05-02 13:41:16,862 - db_handler - INFO - Init DB connection
2019-05-02 13:41:16,919 - discord.client - INFO - logging in using static token
2019-05-02 13:41:19,007 - discord.gateway - INFO - Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
2019-05-02 13:41:19,028 - discord.gateway - INFO - Shard ID None has sent the IDENTIFY payload.
2019-05-02 13:41:19,187 - discord.gateway - INFO - Shard ID None has connected to Gateway: gateway-prd-main-bnfw, discord-sessions-prd-1-26 (Session ID: 62ff8e2b28075291ad4cc533a9b88d9f).
2019-05-02 13:47:55,583 - discord.client - WARNING - PyNaCl is not installed, voice will NOT be supported
2019-05-02 13:52:36,065 - discord.client - WARNING - PyNaCl is not installed, voice will NOT be supported
2019-05-02 13:55:20,252 - discord.client - WARNING - PyNaCl is not installed, voice will NOT be supported
2019-05-02 14:01:00,566 - discord.client - WARNING - PyNaCl is not installed, voice will NOT be supported
2019-05-02 14:01:00,569 - discord.client - INFO - logging in using static token
2019-05-02 14:01:01,818 - discord.gateway - INFO - Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
2019-05-02 14:01:01,823 - discord.gateway - INFO - Shard ID None has sent the IDENTIFY payload.
2019-05-02 14:01:02,012 - discord.gateway - INFO - Shard ID None has connected to Gateway: gateway-prd-main-dp3d, discord-sessions-prd-1-26 (Session ID: 3764d00e4ce4c028da5d03c737ab20fc).
2019-05-02 14:10:39,130 - discord.client - WARNING - PyNaCl is not installed, voice will NOT be supported
2019-05-02 14:10:39,131 - discord.client - INFO - logging in using static token
2019-05-02 14:10:40,504 - discord.gateway - INFO - Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
2019-05-02 14:10:40,510 - discord.gateway - INFO - Shard ID None has sent the IDENTIFY payload.
2019-05-02 14:10:40,655 - discord.gateway - INFO - Shard ID None has connected to Gateway: gateway-prd-main-1zc2, discord-sessions-prd-1-19 (Session ID: 80518cb861e5a8eb84c6728583a01753).
2019-05-02 14:10:42,661 - __main__ - INFO - We have logged in as Snake#5099
2019-05-02 14:18:03,888 - discord.client - WARNING - PyNaCl is not installed, voice will NOT be supported
2019-05-02 14:18:03,890 - discord.client - INFO - logging in using static token
2019-05-02 14:18:05,094 - discord.gateway - INFO - Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
2019-05-02 14:18:05,096 - discord.gateway - INFO - Shard ID None has sent the IDENTIFY payload.
2019-05-02 14:18:05,254 - discord.gateway - INFO - Shard ID None has connected to Gateway: gateway-prd-main-9xgj, discord-sessions-prd-1-13 (Session ID: 3f9394805ea886726f40f9e8335ae8c7).
2019-05-02 14:18:07,260 - __main__ - INFO - We have logged in as Snake#5099
2019-05-02 14:19:42,949 - discord.client - WARNING - PyNaCl is not installed, voice will NOT be supported
2019-05-02 14:19:42,951 - db_handler - INFO - Init DB connection
2019-05-02 14:19:42,961 - db_handler - INFO - Init DB connection
2019-05-02 14:19:43,136 - db_handler - INFO - Init DB connection
2019-05-02 14:19:43,143 - discord.client - INFO - logging in using static token
2019-05-02 14:19:44,527 - discord.gateway - INFO - Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
2019-05-02 14:19:44,533 - discord.gateway - INFO - Shard ID None has sent the IDENTIFY payload.
2019-05-02 14:19:44,699 - discord.gateway - INFO - Shard ID None has connected to Gateway: gateway-prd-main-9h15, discord-sessions-prd-1-3 (Session ID: 59a987ed30f250703f8c5ce97c1fe38a).
2019-05-02 14:19:46,702 - __main__ - INFO - We have logged in as Snake#5099
2019-05-02 14:20:00,654 - db_handler - INFO - {'ally_code': 376764962} found for 143651954919342080
2019-05-02 14:20:01,541 - swgoh_handler - INFO - Response 200 OK
2019-05-02 14:48:59,465 - discord.client - WARNING - PyNaCl is not installed, voice will NOT be supported
2019-05-02 14:48:59,471 - db_handler - INFO - Init DB connection
2019-05-02 14:48:59,485 - db_handler - INFO - Init DB connection
2019-05-02 14:48:59,707 - db_handler - INFO - Init DB connection
2019-05-02 14:48:59,722 - discord.client - INFO - logging in using static token
2019-05-02 14:49:01,258 - discord.gateway - INFO - Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
2019-05-02 14:49:01,261 - discord.gateway - INFO - Shard ID None has sent the IDENTIFY payload.
2019-05-02 14:49:01,412 - discord.gateway - INFO - Shard ID None has connected to Gateway: gateway-prd-main-hq1t, discord-sessions-prd-1-10 (Session ID: 5e46022b7f2582c9c4872bde71f1788d).
2019-05-02 14:49:03,417 - __main__ - INFO - We have logged in as Snake#5099
2019-05-02 14:49:19,767 - db_handler - INFO - {'ally_code': 471941296} found for 269074011185610762
2019-05-02 14:49:20,486 - swgoh_handler - INFO - Response 200 OK
2019-05-02 14:52:53,690 - db_handler - INFO - {'ally_code': 376764962} found for 143651954919342080
2019-05-02 14:52:54,383 - swgoh_handler - INFO - Response 200 OK
2019-05-02 14:54:33,485 - db_handler - INFO - {'ally_code': 376764962} found for 143651954919342080
2019-05-02 14:54:34,140 - swgoh_handler - INFO - Response 200 OK
2019-05-02 15:41:58,563 - discord.client - WARNING - PyNaCl is not installed, voice will NOT be supported
2019-05-02 15:41:58,571 - db_handler - INFO - Init DB connection
2019-05-02 15:41:58,583 - db_handler - INFO - Init DB connection
2019-05-02 15:41:58,786 - db_handler - INFO - Init DB connection
2019-05-02 15:41:58,791 - discord.client - INFO - logging in using static token
2019-05-02 15:41:59,918 - discord.gateway - INFO - Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
2019-05-02 15:41:59,927 - discord.gateway - INFO - Shard ID None has sent the IDENTIFY payload.
2019-05-02 15:42:01,260 - discord.gateway - INFO - Shard ID None has connected to Gateway: gateway-prd-main-z1d0, discord-sessions-prd-1-13 (Session ID: 18ebcfe190240fa19bc8c77422d1a540).
2019-05-02 15:42:01,859 - discord.gateway - WARNING - Unknown event PRESENCES_REPLACE.
2019-05-02 15:42:03,251 - __main__ - INFO - We have logged in as Snake#5099
2019-05-02 15:48:36,520 - discord.client - WARNING - PyNaCl is not installed, voice will NOT be supported
2019-05-02 15:48:36,523 - db_handler - INFO - Init DB connection
2019-05-02 15:48:36,531 - db_handler - INFO - Init DB connection
2019-05-02 15:48:36,708 - db_handler - INFO - Init DB connection
2019-05-02 15:49:34,621 - discord.client - WARNING - PyNaCl is not installed, voice will NOT be supported
2019-05-02 15:49:34,625 - db_handler - INFO - Init DB connection
2019-05-02 15:49:34,635 - db_handler - INFO - Init DB connection
2019-05-02 15:49:34,798 - db_handler - INFO - Init DB connection
2019-05-02 15:49:34,805 - discord.client - INFO - logging in using static token
2019-05-02 15:49:36,029 - discord.gateway - INFO - Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
2019-05-02 15:49:36,032 - discord.gateway - INFO - Shard ID None has sent the IDENTIFY payload.
2019-05-02 15:49:36,208 - discord.gateway - INFO - Shard ID None has connected to Gateway: gateway-prd-main-0q5p, discord-sessions-prd-1-28 (Session ID: 04dd1d848ec34879fb696937890de1a1).
2019-05-02 15:49:38,215 - __main__ - INFO - We have logged in as Snake#5099
2019-05-02 16:00:39,762 - discord.client - WARNING - PyNaCl is not installed, voice will NOT be supported
2019-05-02 16:00:39,774 - db_handler - INFO - Init DB connection
2019-05-02 16:00:39,786 - db_handler - INFO - Init DB connection
2019-05-02 16:00:39,947 - db_handler - INFO - Init DB connection
2019-05-02 16:00:39,952 - discord.client - INFO - logging in using static token
2019-05-02 16:00:41,115 - discord.gateway - INFO - Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
2019-05-02 16:00:41,119 - discord.gateway - INFO - Shard ID None has sent the IDENTIFY payload.
2019-05-02 16:00:41,469 - discord.gateway - INFO - Shard ID None has connected to Gateway: gateway-prd-main-lw5f, discord-sessions-prd-1-16 (Session ID: b62e4129834938b703472e4adb0fe3ed).
2019-05-02 16:00:43,473 - __main__ - INFO - We have logged in as Snake#5099
2019-05-02 16:01:34,299 - discord.client - WARNING - PyNaCl is not installed, voice will NOT be supported
2019-05-02 16:01:34,319 - db_handler - INFO - Init DB connection
2019-05-02 16:01:34,335 - db_handler - INFO - Init DB connection
2019-05-02 16:01:34,607 - db_handler - INFO - Init DB connection
2019-05-02 16:01:34,615 - discord.client - INFO - logging in using static token
2019-05-02 16:01:35,753 - discord.gateway - INFO - Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
2019-05-02 16:01:35,765 - discord.gateway - INFO - Shard ID None has sent the IDENTIFY payload.
2019-05-02 16:01:35,957 - discord.gateway - INFO - Shard ID None has connected to Gateway: gateway-prd-main-2sw1, discord-sessions-prd-1-12 (Session ID: beab339b8635302a06e3ad11cc6e166a).
2019-05-02 16:01:37,959 - __main__ - INFO - We have logged in as Snake#5099
2019-05-02 16:02:34,364 - discord.client - WARNING - PyNaCl is not installed, voice will NOT be supported
2019-05-02 16:02:34,379 - db_handler - INFO - Init DB connection
2019-05-02 16:02:34,394 - db_handler - INFO - Init DB connection
2019-05-02 16:02:34,549 - db_handler - INFO - Init DB connection
2019-05-02 16:02:34,555 - discord.client - INFO - logging in using static token
2019-05-02 16:02:35,690 - discord.gateway - INFO - Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
2019-05-02 16:02:35,694 - discord.gateway - INFO - Shard ID None has sent the IDENTIFY payload.
2019-05-02 16:02:35,865 - discord.gateway - INFO - Shard ID None has connected to Gateway: gateway-prd-main-9h15, discord-sessions-prd-1-8 (Session ID: 67dc8edbef8de6e9fa143d046fa0f5c9).
2019-05-02 16:02:37,868 - __main__ - INFO - We have logged in as Snake#5099
2019-05-02 16:04:18,290 - discord.client - WARNING - PyNaCl is not installed, voice will NOT be supported
2019-05-02 16:26:32,513 - discord.client - WARNING - PyNaCl is not installed, voice will NOT be supported
2019-05-02 16:26:32,528 - db_handler - INFO - Init DB connection
2019-05-02 16:26:32,537 - db_handler - INFO - Init DB connection
2019-05-02 16:26:32,700 - db_handler - INFO - Init DB connection
2019-05-02 16:43:56,248 - discord.client - WARNING - PyNaCl is not installed, voice will NOT be supported
2019-05-02 16:43:56,269 - db_handler - INFO - Init DB connection
2019-05-02 16:43:56,281 - db_handler - INFO - Init DB connection
2019-05-02 16:43:56,483 - db_handler - INFO - Init DB connection
2019-05-02 16:43:56,496 - discord.client - INFO - logging in using static token
2019-05-02 16:43:57,688 - discord.gateway - INFO - Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
2019-05-02 16:43:57,692 - discord.gateway - INFO - Shard ID None has sent the IDENTIFY payload.
2019-05-02 16:43:57,902 - discord.gateway - INFO - Shard ID None has connected to Gateway: gateway-prd-main-hq1t, discord-sessions-prd-1-26 (Session ID: 80f2615d6c7c2c3d2cd3653e82f98af2).
2019-05-02 16:43:59,906 - __main__ - INFO - We have logged in as Snake#5099
2019-05-02 16:45:09,657 - discord.client - WARNING - PyNaCl is not installed, voice will NOT be supported
2019-05-02 16:45:09,670 - db_handler - INFO - Init DB connection
2019-05-02 16:45:09,684 - db_handler - INFO - Init DB connection
2019-05-02 16:45:09,969 - db_handler - INFO - Init DB connection
2019-05-02 16:45:09,996 - discord.client - INFO - logging in using static token
2019-05-02 16:45:11,281 - discord.gateway - INFO - Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
2019-05-02 16:45:11,286 - discord.gateway - INFO - Shard ID None has sent the IDENTIFY payload.
2019-05-02 16:45:11,654 - discord.gateway - INFO - Shard ID None has connected to Gateway: gateway-prd-main-ln45, discord-sessions-prd-1-3 (Session ID: af427c4535b108d47bdab653a0e00d19).
2019-05-02 16:45:13,658 - __main__ - INFO - We have logged in as Snake#5099
2019-05-02 16:46:47,970 - discord.client - WARNING - PyNaCl is not installed, voice will NOT be supported
2019-05-02 16:46:47,980 - db_handler - INFO - Init DB connection
2019-05-02 16:46:47,989 - db_handler - INFO - Init DB connection
2019-05-02 16:46:48,158 - db_handler - INFO - Init DB connection
2019-05-02 16:46:48,164 - discord.client - INFO - logging in using static token
2019-05-02 16:46:49,267 - discord.gateway - INFO - Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
2019-05-02 16:46:49,271 - discord.gateway - INFO - Shard ID None has sent the IDENTIFY payload.
2019-05-02 16:46:49,415 - discord.gateway - INFO - Shard ID None has connected to Gateway: gateway-prd-main-h5b1, discord-sessions-prd-1-8 (Session ID: 456ed41d8f97c18a123d9f62d4b5de10).
2019-05-02 16:46:51,421 - __main__ - INFO - We have logged in as Snake#5099
2019-05-02 16:49:44,606 - discord.client - WARNING - PyNaCl is not installed, voice will NOT be supported
2019-05-02 16:49:44,616 - db_handler - INFO - Init DB connection
2019-05-02 16:49:44,624 - db_handler - INFO - Init DB connection
2019-05-02 16:49:44,786 - db_handler - INFO - Init DB connection
2019-05-02 16:49:44,793 - discord.client - INFO - logging in using static token
2019-05-02 16:49:45,899 - discord.gateway - INFO - Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
2019-05-02 16:49:45,902 - discord.gateway - INFO - Shard ID None has sent the IDENTIFY payload.
2019-05-02 16:49:46,113 - discord.gateway - INFO - Shard ID None has connected to Gateway: gateway-prd-main-xt1j, discord-sessions-prd-1-25 (Session ID: 511255c408b3ca4b01fe745079cf4714).
2019-05-02 16:49:48,120 - __main__ - INFO - We have logged in as Snake#5099
2019-05-02 16:53:42,760 - discord.client - WARNING - PyNaCl is not installed, voice will NOT be supported
2019-05-02 16:53:42,770 - db_handler - INFO - Init DB connection
2019-05-02 16:53:42,784 - db_handler - INFO - Init DB connection
2019-05-02 16:53:42,953 - db_handler - INFO - Init DB connection
2019-05-02 16:53:42,961 - discord.client - INFO - logging in using static token
2019-05-02 16:53:44,129 - discord.gateway - INFO - Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
2019-05-02 16:53:44,134 - discord.gateway - INFO - Shard ID None has sent the IDENTIFY payload.
2019-05-02 16:53:44,317 - discord.gateway - INFO - Shard ID None has connected to Gateway: gateway-prd-main-jg92, discord-sessions-prd-1-8 (Session ID: bc0289f568125db32236f422b37d1a7e).
2019-05-02 16:53:46,306 - __main__ - INFO - We have logged in as Snake#5099
2019-05-02 16:57:05,642 - discord.client - WARNING - PyNaCl is not installed, voice will NOT be supported
2019-05-02 16:57:05,663 - db_handler - INFO - Init DB connection
2019-05-02 16:57:05,685 - db_handler - INFO - Init DB connection
2019-05-02 16:57:05,893 - db_handler - INFO - Init DB connection
2019-05-02 16:57:05,898 - discord.client - INFO - logging in using static token
2019-05-02 16:57:06,959 - discord.gateway - INFO - Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
2019-05-02 16:57:06,961 - discord.gateway - INFO - Shard ID None has sent the IDENTIFY payload.
2019-05-02 16:57:08,197 - discord.gateway - INFO - Shard ID None has connected to Gateway: gateway-prd-main-xt1j, discord-sessions-prd-1-12 (Session ID: f1717e3a484ec82da1d9a3936337eaea).
2019-05-02 16:57:08,484 - discord.gateway - WARNING - Unknown event PRESENCES_REPLACE.
2019-05-02 16:57:10,203 - __main__ - INFO - We have logged in as Snake#5099
2019-05-02 17:03:24,672 - discord.client - WARNING - PyNaCl is not installed, voice will NOT be supported
2019-05-02 17:03:24,679 - db_handler - INFO - Init DB connection
2019-05-02 17:03:24,745 - db_handler - INFO - Init DB connection
2019-05-02 17:03:24,972 - db_handler - INFO - Init DB connection
2019-05-02 17:03:25,016 - discord.client - INFO - logging in using static token
2019-05-02 17:03:26,410 - discord.gateway - INFO - Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
2019-05-02 17:03:26,415 - discord.gateway - INFO - Shard ID None has sent the IDENTIFY payload.
2019-05-02 17:03:26,597 - discord.gateway - INFO - Shard ID None has connected to Gateway: gateway-prd-main-vt0h, discord-sessions-prd-1-26 (Session ID: 2d57daddb816e9d3dd3ee4dde782f6c2).
2019-05-02 17:03:28,602 - __main__ - INFO - We have logged in as Snake#5099
2019-05-02 17:07:04,900 - discord.client - WARNING - PyNaCl is not installed, voice will NOT be supported
2019-05-02 17:07:04,916 - db_handler - INFO - Init DB connection
2019-05-02 17:07:04,925 - db_handler - INFO - Init DB connection
2019-05-02 17:07:05,071 - db_handler - INFO - Init DB connection
2019-05-02 17:07:05,082 - discord.client - INFO - logging in using static token
2019-05-02 17:07:06,114 - discord.gateway - INFO - Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
2019-05-02 17:07:06,117 - discord.gateway - INFO - Shard ID None has sent the IDENTIFY payload.
2019-05-02 17:07:06,259 - discord.gateway - INFO - Shard ID None has connected to Gateway: gateway-prd-main-s47l, discord-sessions-prd-1-6 (Session ID: 374966aa95975b00667c3e93ec019dca).
2019-05-02 17:07:08,263 - __main__ - INFO - We have logged in as Snake#5099
2019-05-02 17:08:05,750 - discord.client - WARNING - PyNaCl is not installed, voice will NOT be supported
2019-05-02 17:08:05,765 - db_handler - INFO - Init DB connection
2019-05-02 17:08:05,774 - db_handler - INFO - Init DB connection
2019-05-02 17:08:05,933 - db_handler - INFO - Init DB connection
2019-05-02 17:08:05,940 - discord.client - INFO - logging in using static token
2019-05-02 17:08:07,020 - discord.gateway - INFO - Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
2019-05-02 17:08:07,028 - discord.gateway - INFO - Shard ID None has sent the IDENTIFY payload.
2019-05-02 17:08:07,174 - discord.gateway - INFO - Shard ID None has connected to Gateway: gateway-prd-main-r48s, discord-sessions-prd-1-8 (Session ID: f9edbd3d71705b3404baf6b53fc8fe8a).
2019-05-02 17:08:09,178 - __main__ - INFO - We have logged in as Snake#5099
2019-05-02 17:10:53,796 - discord.client - WARNING - PyNaCl is not installed, voice will NOT be supported
2019-05-02 17:10:53,800 - db_handler - INFO - Init DB connection
2019-05-02 17:10:53,808 - db_handler - INFO - Init DB connection
2019-05-02 17:10:53,958 - db_handler - INFO - Init DB connection
2019-05-02 19:05:32,726 - discord.client - WARNING - PyNaCl is not installed, voice will NOT be supported
2019-05-02 19:05:32,735 - db_handler - INFO - Init DB connection
2019-05-02 19:05:32,745 - db_handler - INFO - Init DB connection
2019-05-02 19:05:32,924 - db_handler - INFO - Init DB connection
2019-05-02 19:05:32,933 - discord.client - INFO - logging in using static token
2019-05-02 19:05:34,416 - discord.gateway - INFO - Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
2019-05-02 19:05:34,420 - discord.gateway - INFO - Shard ID None has sent the IDENTIFY payload.
2019-05-02 19:05:34,616 - discord.gateway - INFO - Shard ID None has connected to Gateway: gateway-prd-main-01vm, discord-sessions-prd-1-29 (Session ID: b55310cf15ed7821f66352589ec7a861).
2019-05-02 19:05:36,620 - __main__ - INFO - We have logged in as Snake#5099
2019-05-02 19:06:49,391 - discord.client - WARNING - PyNaCl is not installed, voice will NOT be supported
2019-05-02 19:06:49,400 - db_handler - INFO - Init DB connection
2019-05-02 19:06:49,409 - db_handler - INFO - Init DB connection
2019-05-02 19:06:49,529 - db_handler - INFO - Init DB connection
2019-05-02 19:06:49,535 - discord.client - INFO - logging in using static token
2019-05-02 19:06:50,645 - discord.gateway - INFO - Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
2019-05-02 19:06:50,652 - discord.gateway - INFO - Shard ID None has sent the IDENTIFY payload.
2019-05-02 19:06:50,812 - discord.gateway - INFO - Shard ID None has connected to Gateway: gateway-prd-main-zs49, discord-sessions-prd-1-27 (Session ID: 5728daab8d101605324b0fb59d16c7e8).
2019-05-02 19:06:52,819 - __main__ - INFO - We have logged in as Snake#5099
2019-05-02 19:07:31,472 - discord.client - WARNING - PyNaCl is not installed, voice will NOT be supported
2019-05-02 19:07:31,481 - db_handler - INFO - Init DB connection
2019-05-02 19:07:31,489 - db_handler - INFO - Init DB connection
2019-05-02 19:07:31,604 - db_handler - INFO - Init DB connection
2019-05-02 19:07:31,610 - discord.client - INFO - logging in using static token
2019-05-02 19:07:32,762 - discord.gateway - INFO - Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
2019-05-02 19:07:32,770 - discord.gateway - INFO - Shard ID None has sent the IDENTIFY payload.
2019-05-02 19:07:32,968 - discord.gateway - INFO - Shard ID None has connected to Gateway: gateway-prd-main-jg92, discord-sessions-prd-1-14 (Session ID: 4f2283bf8ffe28d1c2d7ae5d307c827d).
2019-05-02 19:07:34,974 - __main__ - INFO - We have logged in as Snake#5099
2019-05-02 19:10:09,275 - discord.client - WARNING - PyNaCl is not installed, voice will NOT be supported
2019-05-02 19:10:09,286 - db_handler - INFO - Init DB connection
2019-05-02 19:10:09,295 - db_handler - INFO - Init DB connection
2019-05-02 19:10:09,448 - db_handler - INFO - Init DB connection
2019-05-02 19:10:09,455 - discord.client - INFO - logging in using static token
2019-05-02 19:10:10,807 - discord.gateway - INFO - Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
2019-05-02 19:10:10,813 - discord.gateway - INFO - Shard ID None has sent the IDENTIFY payload.
2019-05-02 19:10:10,975 - discord.gateway - INFO - Shard ID None has connected to Gateway: gateway-prd-main-2kp3, discord-sessions-prd-1-28 (Session ID: a1528f8e40d8c411d3770f497dbfe305).
2019-05-02 19:10:12,978 - __main__ - INFO - We have logged in as Snake#5099
2019-05-02 19:14:33,035 - discord.client - WARNING - PyNaCl is not installed, voice will NOT be supported
2019-05-02 19:14:33,041 - db_handler - INFO - Init DB connection
2019-05-02 19:14:33,052 - db_handler - INFO - Init DB connection
2019-05-02 19:14:33,186 - db_handler - INFO - Init DB connection
2019-05-02 19:14:33,192 - discord.client - INFO - logging in using static token
2019-05-02 19:14:34,474 - discord.gateway - INFO - Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
2019-05-02 19:14:34,480 - discord.gateway - INFO - Shard ID None has sent the IDENTIFY payload.
2019-05-02 19:14:34,662 - discord.gateway - INFO - Shard ID None has connected to Gateway: gateway-prd-main-njxv, discord-sessions-prd-1-26 (Session ID: afa291b24295ffe2c06da30a13d44c01).
2019-05-02 19:14:36,669 - __main__ - INFO - We have logged in as Snake#5099
2019-05-02 20:58:12,773 - discord.gateway - INFO - Websocket closed with 1006 (), attempting a reconnect.
2019-05-02 20:58:12,773 - discord.client - INFO - Got a request to RESUME the websocket.
2019-05-02 20:58:12,986 - discord.client - ERROR - Attempting a reconnect in 0.46s
Traceback (most recent call last):
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\aiohttp\connector.py", line 955, in _create_direct_connection
    traces=traces), loop=self._loop)
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\aiohttp\connector.py", line 825, in _resolve_host
    self._resolver.resolve(host, port, family=self._family)
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\aiohttp\resolver.py", line 30, in resolve
    host, port, type=socket.SOCK_STREAM, family=family)
  File "d:\python3.6-64\Lib\concurrent\futures\thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "d:\python3.6-64\Lib\socket.py", line 743, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\discord\client.py", line 431, in connect
    await self._connect()
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\discord\client.py", line 401, in _connect
    self.ws = await asyncio.wait_for(coro, timeout=180.0, loop=self.loop)
  File "d:\python3.6-64\Lib\asyncio\tasks.py", line 358, in wait_for
    return fut.result()
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\discord\gateway.py", line 219, in from_client
    gateway = await client.http.get_gateway()
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\discord\http.py", line 786, in get_gateway
    data = await self.request(Route('GET', '/gateway'))
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\discord\http.py", line 158, in request
    async with self.__session.request(method, url, **kwargs) as r:
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\aiohttp\client.py", line 1005, in __aenter__
    self._resp = await self._coro
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\aiohttp\client.py", line 476, in _request
    timeout=real_timeout
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\aiohttp\connector.py", line 522, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\aiohttp\connector.py", line 854, in _create_connection
    req, traces, timeout)
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\aiohttp\connector.py", line 959, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host discordapp.com:443 ssl:None [getaddrinfo failed]
2019-05-02 20:58:19,596 - discord.gateway - INFO - Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
2019-05-02 20:58:19,969 - discord.gateway - INFO - Shard ID None has sent the IDENTIFY payload.
2019-05-02 20:58:20,178 - discord.gateway - INFO - Shard ID None has connected to Gateway: gateway-prd-main-l1kq, discord-sessions-prd-1-18 (Session ID: 6cdc70ce96cfa5b89c9d4210d1c236f5).
2019-05-02 20:58:22,181 - __main__ - INFO - We have logged in as Snake#5099
2019-05-02 20:58:42,061 - discord.gateway - WARNING - Shard ID None has stopped responding to the gateway. Closing and restarting.
2019-05-02 21:03:48,375 - discord.client - WARNING - PyNaCl is not installed, voice will NOT be supported
2019-05-02 21:03:48,380 - db_handler - INFO - Init DB connection
2019-05-02 21:03:48,390 - db_handler - INFO - Init DB connection
2019-05-02 21:03:48,539 - db_handler - INFO - Init DB connection
2019-05-02 21:03:48,545 - discord.client - INFO - logging in using static token
2019-05-02 21:03:49,818 - discord.gateway - INFO - Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
2019-05-02 21:03:49,827 - discord.gateway - INFO - Shard ID None has sent the IDENTIFY payload.
2019-05-02 21:03:49,997 - discord.gateway - INFO - Shard ID None has connected to Gateway: gateway-prd-main-z3p2, discord-sessions-prd-1-18 (Session ID: d4721d1473106d8bd6950b1629451a7d).
2019-05-02 21:03:52,005 - __main__ - INFO - We have logged in as Snake#5099
2019-05-02 21:05:31,906 - discord.client - WARNING - PyNaCl is not installed, voice will NOT be supported
2019-05-02 21:05:31,912 - db_handler - INFO - Init DB connection
2019-05-02 21:05:31,923 - db_handler - INFO - Init DB connection
2019-05-02 21:05:32,057 - db_handler - INFO - Init DB connection
2019-05-02 21:05:32,062 - discord.client - INFO - logging in using static token
2019-05-02 21:05:33,336 - discord.gateway - INFO - Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
2019-05-02 21:05:33,339 - discord.gateway - INFO - Shard ID None has sent the IDENTIFY payload.
2019-05-02 21:05:33,586 - discord.gateway - INFO - Shard ID None has connected to Gateway: gateway-prd-main-nzxs, discord-sessions-prd-1-9 (Session ID: 4812e965838ae4619245d3ae4674cd88).
2019-05-02 21:05:35,591 - __main__ - INFO - We have logged in as Snake#5099
2019-05-02 21:21:58,476 - discord.client - WARNING - PyNaCl is not installed, voice will NOT be supported
2019-05-02 21:21:58,481 - db_handler - INFO - Init DB connection
2019-05-02 21:21:58,489 - db_handler - INFO - Init DB connection
2019-05-02 21:21:58,607 - db_handler - INFO - Init DB connection
2019-05-02 21:21:58,613 - discord.client - INFO - logging in using static token
2019-05-02 21:21:59,795 - discord.gateway - INFO - Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
2019-05-02 21:21:59,803 - discord.gateway - INFO - Shard ID None has sent the IDENTIFY payload.
2019-05-02 21:22:00,830 - discord.gateway - INFO - Shard ID None has connected to Gateway: gateway-prd-main-v0r8, discord-sessions-prd-1-26 (Session ID: 6270774ddbb4dae0feb868cea5a808db).
2019-05-02 21:22:02,837 - __main__ - INFO - We have logged in as Snake#5099
2019-05-02 21:45:08,455 - discord.client - WARNING - PyNaCl is not installed, voice will NOT be supported
2019-05-02 21:45:08,458 - db_handler - INFO - Init DB connection
2019-05-02 21:45:08,467 - db_handler - INFO - Init DB connection
2019-05-02 21:45:08,605 - db_handler - INFO - Init DB connection
2019-05-02 21:45:08,611 - discord.client - INFO - logging in using static token
2019-05-02 21:45:09,728 - discord.gateway - INFO - Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
2019-05-02 21:45:09,733 - discord.gateway - INFO - Shard ID None has sent the IDENTIFY payload.
2019-05-02 21:45:09,894 - discord.gateway - INFO - Shard ID None has connected to Gateway: gateway-prd-main-890b, discord-sessions-prd-1-8 (Session ID: ca875fdf3dfbb2a29b34312064281ed6).
2019-05-02 21:45:11,904 - __main__ - INFO - We have logged in as Snake#5099
2019-05-03 11:46:56,108 - discord.client - WARNING - PyNaCl is not installed, voice will NOT be supported
2019-05-03 11:46:56,155 - db_handler - INFO - Init DB connection
2019-05-03 11:46:56,165 - db_handler - INFO - Init DB connection
2019-05-03 11:46:56,426 - db_handler - INFO - Init DB connection
2019-05-03 11:47:51,445 - discord.client - WARNING - PyNaCl is not installed, voice will NOT be supported
2019-05-03 11:47:51,449 - db_handler - INFO - Init DB connection
2019-05-03 11:47:51,461 - db_handler - INFO - Init DB connection
2019-05-03 11:47:51,643 - db_handler - INFO - Init DB connection
2019-05-04 15:42:18,433 - discord.client - WARNING - PyNaCl is not installed, voice will NOT be supported
2019-05-04 15:42:18,473 - discord.client - INFO - logging in using static token
2019-05-04 15:42:20,102 - discord.gateway - INFO - Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
2019-05-04 15:42:20,116 - discord.gateway - INFO - Shard ID None has sent the IDENTIFY payload.
2019-05-04 15:42:20,319 - discord.gateway - INFO - Shard ID None has connected to Gateway: gateway-prd-main-xsd1, discord-sessions-prd-1-22 (Session ID: 39be72af2a95b30c64201d3710ab92d1).
2019-05-04 15:49:04,212 - discord.client - WARNING - PyNaCl is not installed, voice will NOT be supported
2019-05-04 15:49:04,521 - discord.client - INFO - logging in using static token
2019-05-04 15:49:05,968 - discord.gateway - INFO - Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
2019-05-04 15:49:05,974 - discord.gateway - INFO - Shard ID None has sent the IDENTIFY payload.
2019-05-04 15:49:06,159 - discord.gateway - INFO - Shard ID None has connected to Gateway: gateway-prd-main-bnfw, discord-sessions-prd-1-26 (Session ID: ec6c66fa85d1410906ffacd1441efa35).
2019-05-04 19:01:58,578 - discord.gateway - INFO - Websocket closed with 1006 (), attempting a reconnect.
2019-05-04 19:01:58,578 - discord.client - INFO - Got a request to RESUME the websocket.
2019-05-04 19:01:58,687 - discord.client - ERROR - Attempting a reconnect in 0.07s
Traceback (most recent call last):
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\aiohttp\connector.py", line 955, in _create_direct_connection
    traces=traces), loop=self._loop)
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\aiohttp\connector.py", line 825, in _resolve_host
    self._resolver.resolve(host, port, family=self._family)
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\aiohttp\resolver.py", line 30, in resolve
    host, port, type=socket.SOCK_STREAM, family=family)
  File "d:\python3.6-64\Lib\concurrent\futures\thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "d:\python3.6-64\Lib\socket.py", line 743, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\discord\client.py", line 431, in connect
    await self._connect()
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\discord\client.py", line 401, in _connect
    self.ws = await asyncio.wait_for(coro, timeout=180.0, loop=self.loop)
  File "d:\python3.6-64\Lib\asyncio\tasks.py", line 358, in wait_for
    return fut.result()
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\discord\gateway.py", line 219, in from_client
    gateway = await client.http.get_gateway()
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\discord\http.py", line 786, in get_gateway
    data = await self.request(Route('GET', '/gateway'))
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\discord\http.py", line 158, in request
    async with self.__session.request(method, url, **kwargs) as r:
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\aiohttp\client.py", line 1005, in __aenter__
    self._resp = await self._coro
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\aiohttp\client.py", line 476, in _request
    timeout=real_timeout
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\aiohttp\connector.py", line 522, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\aiohttp\connector.py", line 854, in _create_connection
    req, traces, timeout)
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\aiohttp\connector.py", line 959, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host discordapp.com:443 ssl:None [getaddrinfo failed]
2019-05-04 19:02:02,450 - discord.client - ERROR - Attempting a reconnect in 3.28s
Traceback (most recent call last):
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\aiohttp\connector.py", line 955, in _create_direct_connection
    traces=traces), loop=self._loop)
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\aiohttp\connector.py", line 825, in _resolve_host
    self._resolver.resolve(host, port, family=self._family)
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\aiohttp\resolver.py", line 30, in resolve
    host, port, type=socket.SOCK_STREAM, family=family)
  File "d:\python3.6-64\Lib\concurrent\futures\thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "d:\python3.6-64\Lib\socket.py", line 743, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\discord\client.py", line 431, in connect
    await self._connect()
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\discord\client.py", line 392, in _connect
    self.ws = await asyncio.wait_for(coro, timeout=180.0, loop=self.loop)
  File "d:\python3.6-64\Lib\asyncio\tasks.py", line 358, in wait_for
    return fut.result()
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\discord\gateway.py", line 219, in from_client
    gateway = await client.http.get_gateway()
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\discord\http.py", line 786, in get_gateway
    data = await self.request(Route('GET', '/gateway'))
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\discord\http.py", line 158, in request
    async with self.__session.request(method, url, **kwargs) as r:
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\aiohttp\client.py", line 1005, in __aenter__
    self._resp = await self._coro
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\aiohttp\client.py", line 476, in _request
    timeout=real_timeout
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\aiohttp\connector.py", line 522, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\aiohttp\connector.py", line 854, in _create_connection
    req, traces, timeout)
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\aiohttp\connector.py", line 959, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host discordapp.com:443 ssl:None [getaddrinfo failed]
2019-05-04 19:02:04,985 - discord.gateway - WARNING - Shard ID None has stopped responding to the gateway. Closing and restarting.
2019-05-04 19:02:06,007 - discord.client - ERROR - Attempting a reconnect in 0.94s
Traceback (most recent call last):
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\aiohttp\connector.py", line 955, in _create_direct_connection
    traces=traces), loop=self._loop)
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\aiohttp\connector.py", line 825, in _resolve_host
    self._resolver.resolve(host, port, family=self._family)
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\aiohttp\resolver.py", line 30, in resolve
    host, port, type=socket.SOCK_STREAM, family=family)
  File "d:\python3.6-64\Lib\concurrent\futures\thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "d:\python3.6-64\Lib\socket.py", line 743, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\discord\client.py", line 431, in connect
    await self._connect()
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\discord\client.py", line 392, in _connect
    self.ws = await asyncio.wait_for(coro, timeout=180.0, loop=self.loop)
  File "d:\python3.6-64\Lib\asyncio\tasks.py", line 358, in wait_for
    return fut.result()
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\discord\gateway.py", line 219, in from_client
    gateway = await client.http.get_gateway()
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\discord\http.py", line 786, in get_gateway
    data = await self.request(Route('GET', '/gateway'))
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\discord\http.py", line 158, in request
    async with self.__session.request(method, url, **kwargs) as r:
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\aiohttp\client.py", line 1005, in __aenter__
    self._resp = await self._coro
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\aiohttp\client.py", line 476, in _request
    timeout=real_timeout
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\aiohttp\connector.py", line 522, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\aiohttp\connector.py", line 854, in _create_connection
    req, traces, timeout)
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\aiohttp\connector.py", line 959, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host discordapp.com:443 ssl:None [getaddrinfo failed]
2019-05-04 19:02:07,164 - discord.client - ERROR - Attempting a reconnect in 2.45s
Traceback (most recent call last):
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\aiohttp\connector.py", line 955, in _create_direct_connection
    traces=traces), loop=self._loop)
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\aiohttp\connector.py", line 825, in _resolve_host
    self._resolver.resolve(host, port, family=self._family)
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\aiohttp\resolver.py", line 30, in resolve
    host, port, type=socket.SOCK_STREAM, family=family)
  File "d:\python3.6-64\Lib\concurrent\futures\thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "d:\python3.6-64\Lib\socket.py", line 743, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\discord\client.py", line 431, in connect
    await self._connect()
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\discord\client.py", line 392, in _connect
    self.ws = await asyncio.wait_for(coro, timeout=180.0, loop=self.loop)
  File "d:\python3.6-64\Lib\asyncio\tasks.py", line 358, in wait_for
    return fut.result()
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\discord\gateway.py", line 219, in from_client
    gateway = await client.http.get_gateway()
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\discord\http.py", line 786, in get_gateway
    data = await self.request(Route('GET', '/gateway'))
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\discord\http.py", line 158, in request
    async with self.__session.request(method, url, **kwargs) as r:
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\aiohttp\client.py", line 1005, in __aenter__
    self._resp = await self._coro
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\aiohttp\client.py", line 476, in _request
    timeout=real_timeout
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\aiohttp\connector.py", line 522, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\aiohttp\connector.py", line 854, in _create_connection
    req, traces, timeout)
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\aiohttp\connector.py", line 959, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host discordapp.com:443 ssl:None [getaddrinfo failed]
2019-05-04 19:02:11,118 - discord.gateway - INFO - Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
2019-05-04 19:02:11,233 - discord.gateway - INFO - Shard ID None has sent the IDENTIFY payload.
2019-05-04 20:18:59,460 - discord.gateway - INFO - Websocket closed with 1006 (), attempting a reconnect.
2019-05-04 20:18:59,461 - discord.client - INFO - Got a request to RESUME the websocket.
2019-05-04 20:19:02,374 - discord.client - ERROR - Attempting a reconnect in 0.06s
Traceback (most recent call last):
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\aiohttp\connector.py", line 955, in _create_direct_connection
    traces=traces), loop=self._loop)
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\aiohttp\connector.py", line 825, in _resolve_host
    self._resolver.resolve(host, port, family=self._family)
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\aiohttp\resolver.py", line 30, in resolve
    host, port, type=socket.SOCK_STREAM, family=family)
  File "d:\python3.6-64\Lib\concurrent\futures\thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "d:\python3.6-64\Lib\socket.py", line 743, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\discord\client.py", line 431, in connect
    await self._connect()
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\discord\client.py", line 401, in _connect
    self.ws = await asyncio.wait_for(coro, timeout=180.0, loop=self.loop)
  File "d:\python3.6-64\Lib\asyncio\tasks.py", line 358, in wait_for
    return fut.result()
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\discord\gateway.py", line 219, in from_client
    gateway = await client.http.get_gateway()
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\discord\http.py", line 786, in get_gateway
    data = await self.request(Route('GET', '/gateway'))
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\discord\http.py", line 158, in request
    async with self.__session.request(method, url, **kwargs) as r:
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\aiohttp\client.py", line 1005, in __aenter__
    self._resp = await self._coro
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\aiohttp\client.py", line 476, in _request
    timeout=real_timeout
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\aiohttp\connector.py", line 522, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\aiohttp\connector.py", line 854, in _create_connection
    req, traces, timeout)
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\aiohttp\connector.py", line 959, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host discordapp.com:443 ssl:None [getaddrinfo failed]
2019-05-04 20:19:04,137 - discord.gateway - INFO - Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
2019-05-04 20:19:04,485 - discord.gateway - INFO - Shard ID None has sent the IDENTIFY payload.
2019-05-04 20:19:04,760 - discord.gateway - INFO - Shard ID None has connected to Gateway: gateway-prd-main-26fh, discord-sessions-prd-1-17 (Session ID: 3abf74ff9b99087413aca32650e280bc).
2019-05-04 20:19:21,911 - discord.gateway - WARNING - Shard ID None has stopped responding to the gateway. Closing and restarting.
2019-05-04 20:58:46,314 - discord.client - WARNING - PyNaCl is not installed, voice will NOT be supported
2019-05-04 21:00:21,071 - discord.client - WARNING - PyNaCl is not installed, voice will NOT be supported
2019-05-04 21:00:21,369 - db_handler - INFO - Init DB connection
2019-05-04 21:00:21,433 - db_handler - INFO - Init DB connection
2019-05-04 21:00:21,898 - db_handler - INFO - Init DB connection
2019-05-04 21:00:21,913 - discord.client - INFO - logging in using static token
2019-05-04 21:00:23,019 - discord.gateway - INFO - Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
2019-05-04 21:00:23,025 - discord.gateway - INFO - Shard ID None has sent the IDENTIFY payload.
2019-05-04 21:00:23,224 - discord.gateway - INFO - Shard ID None has connected to Gateway: gateway-prd-main-dg6v, discord-sessions-prd-1-5 (Session ID: fe9feb2c3685f401da2bd46dcc85e039).
2019-05-04 21:00:25,230 - __main__ - INFO - We have logged in as Snake#5099
2019-05-04 21:01:27,796 - discord.client - WARNING - PyNaCl is not installed, voice will NOT be supported
2019-05-04 21:01:27,799 - db_handler - INFO - Init DB connection
2019-05-04 21:01:27,807 - db_handler - INFO - Init DB connection
2019-05-04 21:01:27,926 - db_handler - INFO - Init DB connection
2019-05-04 21:01:28,216 - discord.client - INFO - logging in using static token
2019-05-04 21:01:29,212 - discord.gateway - INFO - Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
2019-05-04 21:01:29,217 - discord.gateway - INFO - Shard ID None has sent the IDENTIFY payload.
2019-05-04 21:01:29,937 - discord.gateway - INFO - Shard ID None has connected to Gateway: gateway-prd-main-4x4m, discord-sessions-prd-1-16 (Session ID: da66376dcea7f98c0cf6e2f589dac78d).
2019-05-04 21:01:31,941 - __main__ - INFO - We have logged in as Snake#5099
2019-05-04 21:03:57,036 - discord.client - WARNING - PyNaCl is not installed, voice will NOT be supported
2019-05-04 21:03:57,038 - db_handler - INFO - Init DB connection
2019-05-04 21:03:57,047 - db_handler - INFO - Init DB connection
2019-05-04 21:03:57,153 - db_handler - INFO - Init DB connection
2019-05-04 21:03:57,160 - discord.client - INFO - logging in using static token
2019-05-04 21:03:58,528 - discord.gateway - INFO - Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
2019-05-04 21:03:58,532 - discord.gateway - INFO - Shard ID None has sent the IDENTIFY payload.
2019-05-04 21:03:58,698 - discord.gateway - INFO - Shard ID None has connected to Gateway: gateway-prd-main-1lwq, discord-sessions-prd-1-21 (Session ID: 95fb42c758b0880c333cf95526f71164).
2019-05-04 21:04:00,690 - __main__ - INFO - We have logged in as Snake#5099
2019-05-04 21:04:52,977 - discord.client - WARNING - PyNaCl is not installed, voice will NOT be supported
2019-05-04 21:04:52,980 - db_handler - INFO - Init DB connection
2019-05-04 21:04:52,988 - db_handler - INFO - Init DB connection
2019-05-04 21:04:53,095 - db_handler - INFO - Init DB connection
2019-05-04 21:04:53,102 - discord.client - INFO - logging in using static token
2019-05-04 21:04:54,128 - discord.gateway - INFO - Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
2019-05-04 21:04:54,137 - discord.gateway - INFO - Shard ID None has sent the IDENTIFY payload.
2019-05-04 21:04:54,334 - discord.gateway - INFO - Shard ID None has connected to Gateway: gateway-prd-main-vt0h, discord-sessions-prd-1-17 (Session ID: df009d4c183e5bdeb524d90cc283dd91).
2019-05-04 21:04:56,338 - __main__ - INFO - We have logged in as Snake#5099
2019-05-04 21:06:58,131 - discord.client - WARNING - PyNaCl is not installed, voice will NOT be supported
2019-05-04 21:06:58,134 - db_handler - INFO - Init DB connection
2019-05-04 21:06:58,141 - db_handler - INFO - Init DB connection
2019-05-04 21:06:58,246 - db_handler - INFO - Init DB connection
2019-05-04 21:06:58,253 - discord.client - INFO - logging in using static token
2019-05-04 21:06:59,407 - discord.gateway - INFO - Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
2019-05-04 21:06:59,409 - discord.gateway - INFO - Shard ID None has sent the IDENTIFY payload.
2019-05-04 21:06:59,569 - discord.gateway - INFO - Shard ID None has connected to Gateway: gateway-prd-main-rwdh, discord-sessions-prd-1-2 (Session ID: 85ea83f18527c198e3dc179bbfa20143).
2019-05-04 21:07:01,578 - __main__ - INFO - We have logged in as Snake#5099
2019-05-04 21:09:22,243 - discord.client - WARNING - PyNaCl is not installed, voice will NOT be supported
2019-05-04 21:09:22,247 - db_handler - INFO - Init DB connection
2019-05-04 21:09:22,275 - db_handler - INFO - Init DB connection
2019-05-04 21:09:22,419 - db_handler - INFO - Init DB connection
2019-05-04 21:09:22,427 - discord.client - INFO - logging in using static token
2019-05-04 21:09:23,462 - discord.gateway - INFO - Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
2019-05-04 21:09:23,467 - discord.gateway - INFO - Shard ID None has sent the IDENTIFY payload.
2019-05-04 21:09:24,051 - discord.gateway - INFO - Shard ID None has connected to Gateway: gateway-prd-main-1wpr, discord-sessions-prd-1-2 (Session ID: 2358a89f2862a81e0652e8fe3094d624).
2019-05-04 21:09:26,057 - __main__ - INFO - We have logged in as Snake#5099
2019-05-04 21:10:46,903 - discord.client - WARNING - PyNaCl is not installed, voice will NOT be supported
2019-05-04 21:10:46,906 - db_handler - INFO - Init DB connection
2019-05-04 21:10:46,915 - db_handler - INFO - Init DB connection
2019-05-04 21:10:47,033 - db_handler - INFO - Init DB connection
2019-05-04 21:10:47,040 - discord.client - INFO - logging in using static token
2019-05-04 21:10:48,282 - discord.gateway - INFO - Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
2019-05-04 21:10:48,284 - discord.gateway - INFO - Shard ID None has sent the IDENTIFY payload.
2019-05-04 21:10:48,518 - discord.gateway - INFO - Shard ID None has connected to Gateway: gateway-prd-main-9xgj, discord-sessions-prd-1-24 (Session ID: e0013a0ec99ee0d4003cf436cd8564a1).
2019-05-04 21:10:50,524 - __main__ - INFO - We have logged in as Snake#5099
2019-05-04 21:14:11,733 - discord.client - WARNING - PyNaCl is not installed, voice will NOT be supported
2019-05-04 21:14:11,736 - db_handler - INFO - Init DB connection
2019-05-04 21:14:11,744 - db_handler - INFO - Init DB connection
2019-05-04 21:14:11,858 - db_handler - INFO - Init DB connection
2019-05-04 21:14:11,866 - discord.client - INFO - logging in using static token
2019-05-04 21:14:13,049 - discord.gateway - INFO - Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
2019-05-04 21:14:13,054 - discord.gateway - INFO - Shard ID None has sent the IDENTIFY payload.
2019-05-04 21:14:13,264 - discord.gateway - INFO - Shard ID None has connected to Gateway: gateway-prd-main-bvj9, discord-sessions-prd-1-9 (Session ID: e2d50ec065bba2fec467eda85194b21a).
2019-05-04 21:14:15,269 - __main__ - INFO - We have logged in as Snake#5099
2019-05-04 21:14:36,524 - discord.client - WARNING - PyNaCl is not installed, voice will NOT be supported
2019-05-04 21:14:36,527 - db_handler - INFO - Init DB connection
2019-05-04 21:14:36,536 - db_handler - INFO - Init DB connection
2019-05-04 21:14:36,670 - db_handler - INFO - Init DB connection
2019-05-04 21:14:36,677 - discord.client - INFO - logging in using static token
2019-05-04 21:14:37,759 - discord.gateway - INFO - Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
2019-05-04 21:14:37,761 - discord.gateway - INFO - Shard ID None has sent the IDENTIFY payload.
2019-05-04 21:14:37,977 - discord.gateway - INFO - Shard ID None has connected to Gateway: gateway-prd-main-10mv, discord-sessions-prd-1-12 (Session ID: 5ff2e713213b06a85d7e51be70b20f63).
2019-05-04 21:14:39,972 - __main__ - INFO - We have logged in as Snake#5099
2019-05-04 21:16:44,534 - discord.client - WARNING - PyNaCl is not installed, voice will NOT be supported
2019-05-04 21:16:44,537 - db_handler - INFO - Init DB connection
2019-05-04 21:16:44,545 - db_handler - INFO - Init DB connection
2019-05-04 21:16:44,645 - db_handler - INFO - Init DB connection
2019-05-04 21:16:44,653 - discord.client - INFO - logging in using static token
2019-05-04 21:16:45,913 - discord.gateway - INFO - Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
2019-05-04 21:16:46,028 - discord.gateway - INFO - Shard ID None has sent the IDENTIFY payload.
2019-05-04 21:16:46,497 - discord.gateway - INFO - Shard ID None has connected to Gateway: gateway-prd-main-gfs7, discord-sessions-prd-1-6 (Session ID: b02076f51992d77aa0f49d93bfec5eb8).
2019-05-04 21:16:48,494 - __main__ - INFO - We have logged in as Snake#5099
2019-05-04 21:17:20,700 - discord.client - WARNING - PyNaCl is not installed, voice will NOT be supported
2019-05-04 21:17:20,706 - db_handler - INFO - Init DB connection
2019-05-04 21:17:20,722 - db_handler - INFO - Init DB connection
2019-05-04 21:17:20,915 - db_handler - INFO - Init DB connection
2019-05-04 21:17:20,936 - discord.client - INFO - logging in using static token
2019-05-04 21:17:22,783 - discord.gateway - INFO - Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
2019-05-04 21:17:22,822 - discord.gateway - INFO - Shard ID None has sent the IDENTIFY payload.
2019-05-04 21:17:23,211 - discord.gateway - INFO - Shard ID None has connected to Gateway: gateway-prd-main-hq1t, discord-sessions-prd-1-8 (Session ID: 71319be4a71dd0a03f2fc588b834e23a).
2019-05-04 21:17:25,210 - __main__ - INFO - We have logged in as Snake#5099
2019-05-04 21:19:27,022 - discord.client - WARNING - PyNaCl is not installed, voice will NOT be supported
2019-05-04 21:19:27,025 - db_handler - INFO - Init DB connection
2019-05-04 21:19:27,033 - db_handler - INFO - Init DB connection
2019-05-04 21:19:27,147 - db_handler - INFO - Init DB connection
2019-05-04 21:19:27,156 - discord.client - INFO - logging in using static token
2019-05-04 21:19:28,237 - discord.gateway - INFO - Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
2019-05-04 21:19:28,244 - discord.gateway - INFO - Shard ID None has sent the IDENTIFY payload.
2019-05-04 21:19:28,442 - discord.gateway - INFO - Shard ID None has connected to Gateway: gateway-prd-main-qv96, discord-sessions-prd-1-2 (Session ID: 85464c283ecc6039cc728363106c1876).
2019-05-04 21:19:30,449 - __main__ - INFO - We have logged in as Snake#5099
2019-05-04 21:19:58,619 - discord.client - WARNING - PyNaCl is not installed, voice will NOT be supported
2019-05-04 21:19:58,622 - db_handler - INFO - Init DB connection
2019-05-04 21:19:58,630 - db_handler - INFO - Init DB connection
2019-05-04 21:19:58,738 - db_handler - INFO - Init DB connection
2019-05-04 21:19:58,750 - discord.client - INFO - logging in using static token
2019-05-04 21:19:59,938 - discord.gateway - INFO - Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
2019-05-04 21:19:59,946 - discord.gateway - INFO - Shard ID None has sent the IDENTIFY payload.
2019-05-04 21:20:00,164 - discord.gateway - INFO - Shard ID None has connected to Gateway: gateway-prd-main-nrxf, discord-sessions-prd-1-13 (Session ID: e9d23dae5eb3b16f1e0a34b318567b7a).
2019-05-04 21:20:02,166 - __main__ - INFO - We have logged in as Snake#5099
2019-05-04 21:22:30,850 - discord.client - WARNING - PyNaCl is not installed, voice will NOT be supported
2019-05-04 21:22:30,852 - db_handler - INFO - Init DB connection
2019-05-04 21:22:30,860 - db_handler - INFO - Init DB connection
2019-05-04 21:22:30,978 - db_handler - INFO - Init DB connection
2019-05-04 21:22:30,992 - discord.client - INFO - logging in using static token
2019-05-04 21:22:32,213 - discord.gateway - INFO - Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
2019-05-04 21:22:32,255 - discord.gateway - INFO - Shard ID None has sent the IDENTIFY payload.
2019-05-04 21:22:33,497 - discord.gateway - INFO - Shard ID None has connected to Gateway: gateway-prd-main-xp0j, discord-sessions-prd-1-20 (Session ID: 089c816644b63ac344be7bc131ab99c6).
2019-05-04 21:22:35,488 - __main__ - INFO - We have logged in as Snake#5099
2019-05-04 21:23:19,947 - discord.client - WARNING - PyNaCl is not installed, voice will NOT be supported
2019-05-04 21:23:19,949 - db_handler - INFO - Init DB connection
2019-05-04 21:23:19,957 - db_handler - INFO - Init DB connection
2019-05-04 21:23:20,063 - db_handler - INFO - Init DB connection
2019-05-04 21:23:20,070 - discord.client - INFO - logging in using static token
2019-05-04 21:23:21,055 - discord.gateway - INFO - Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
2019-05-04 21:23:21,064 - discord.gateway - INFO - Shard ID None has sent the IDENTIFY payload.
2019-05-04 21:23:21,229 - discord.gateway - INFO - Shard ID None has connected to Gateway: gateway-prd-main-dg6v, discord-sessions-prd-1-6 (Session ID: 7ff81b62f3aabc6300abafcae28f58a2).
2019-05-04 21:23:23,234 - __main__ - INFO - We have logged in as Snake#5099
2019-05-04 21:25:17,459 - discord.client - WARNING - PyNaCl is not installed, voice will NOT be supported
2019-05-04 21:25:17,462 - db_handler - INFO - Init DB connection
2019-05-04 21:25:17,469 - db_handler - INFO - Init DB connection
2019-05-04 21:25:17,593 - db_handler - INFO - Init DB connection
2019-05-04 21:25:17,601 - discord.client - INFO - logging in using static token
2019-05-04 21:25:18,596 - discord.gateway - INFO - Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
2019-05-04 21:25:18,600 - discord.gateway - INFO - Shard ID None has sent the IDENTIFY payload.
2019-05-04 21:25:18,834 - discord.gateway - INFO - Shard ID None has connected to Gateway: gateway-prd-main-v0r8, discord-sessions-prd-1-27 (Session ID: 3baf361b0861c5b5310d31a5a67f4584).
2019-05-04 21:25:20,839 - __main__ - INFO - We have logged in as Snake#5099
2019-05-04 21:26:12,735 - discord.client - WARNING - PyNaCl is not installed, voice will NOT be supported
2019-05-04 21:26:12,738 - db_handler - INFO - Init DB connection
2019-05-04 21:26:12,747 - db_handler - INFO - Init DB connection
2019-05-04 21:26:12,871 - db_handler - INFO - Init DB connection
2019-05-04 21:26:12,883 - discord.client - INFO - logging in using static token
2019-05-04 21:26:14,381 - discord.gateway - INFO - Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
2019-05-04 21:26:14,585 - discord.gateway - INFO - Shard ID None has sent the IDENTIFY payload.
2019-05-04 21:26:15,061 - discord.gateway - INFO - Shard ID None has connected to Gateway: gateway-prd-main-2kp3, discord-sessions-prd-1-2 (Session ID: e1baf382751de142520656e6725243fb).
2019-05-04 21:26:17,075 - __main__ - INFO - We have logged in as Snake#5099
2019-05-04 21:28:21,160 - discord.client - WARNING - PyNaCl is not installed, voice will NOT be supported
2019-05-04 21:28:21,163 - db_handler - INFO - Init DB connection
2019-05-04 21:28:21,172 - db_handler - INFO - Init DB connection
2019-05-04 21:28:21,287 - db_handler - INFO - Init DB connection
2019-05-04 21:28:21,296 - discord.client - INFO - logging in using static token
2019-05-04 21:28:22,358 - discord.gateway - INFO - Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
2019-05-04 21:28:22,362 - discord.gateway - INFO - Shard ID None has sent the IDENTIFY payload.
2019-05-04 21:28:22,853 - discord.gateway - INFO - Shard ID None has connected to Gateway: gateway-prd-main-9xgj, discord-sessions-prd-1-5 (Session ID: 99c6f8b4cb032f73f2adbecdfed957e4).
2019-05-04 21:28:24,857 - __main__ - INFO - We have logged in as Snake#5099
2019-05-04 21:29:31,134 - discord.client - WARNING - PyNaCl is not installed, voice will NOT be supported
2019-05-04 21:29:31,136 - db_handler - INFO - Init DB connection
2019-05-04 21:29:31,144 - db_handler - INFO - Init DB connection
2019-05-04 21:29:31,262 - db_handler - INFO - Init DB connection
2019-05-04 21:29:31,269 - discord.client - INFO - logging in using static token
2019-05-04 21:29:32,315 - discord.gateway - INFO - Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
2019-05-04 21:29:32,320 - discord.gateway - INFO - Shard ID None has sent the IDENTIFY payload.
2019-05-04 21:29:32,960 - discord.gateway - INFO - Shard ID None has connected to Gateway: gateway-prd-main-26sm, discord-sessions-prd-1-18 (Session ID: 72b97f488911648d3329a3cbe746fe45).
2019-05-04 21:29:34,968 - __main__ - INFO - We have logged in as Snake#5099
2019-05-04 21:38:23,201 - discord.client - WARNING - PyNaCl is not installed, voice will NOT be supported
2019-05-04 21:38:23,204 - db_handler - INFO - Init DB connection
2019-05-04 21:38:23,211 - db_handler - INFO - Init DB connection
2019-05-04 21:38:23,326 - db_handler - INFO - Init DB connection
2019-05-04 21:38:23,334 - discord.client - INFO - logging in using static token
2019-05-04 21:38:24,840 - discord.gateway - INFO - Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
2019-05-04 21:38:24,844 - discord.gateway - INFO - Shard ID None has sent the IDENTIFY payload.
2019-05-04 21:38:25,089 - discord.gateway - INFO - Shard ID None has connected to Gateway: gateway-prd-main-l420, discord-sessions-prd-1-9 (Session ID: 351797a04b5b86fa0b43258efaeb1b10).
2019-05-04 21:38:27,092 - __main__ - INFO - We have logged in as Snake#5099
2019-05-04 21:39:46,245 - discord.client - WARNING - PyNaCl is not installed, voice will NOT be supported
2019-05-04 21:39:46,248 - db_handler - INFO - Init DB connection
2019-05-04 21:39:46,257 - db_handler - INFO - Init DB connection
2019-05-04 21:39:46,377 - db_handler - INFO - Init DB connection
2019-05-04 21:39:46,392 - discord.client - INFO - logging in using static token
2019-05-04 21:39:47,495 - discord.gateway - INFO - Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
2019-05-04 21:39:47,503 - discord.gateway - INFO - Shard ID None has sent the IDENTIFY payload.
2019-05-04 21:39:47,781 - discord.gateway - INFO - Shard ID None has connected to Gateway: gateway-prd-main-z0zz, discord-sessions-prd-1-9 (Session ID: a817ed5ac9f3d4f741fd62b7896d54c6).
2019-05-04 21:39:49,785 - __main__ - INFO - We have logged in as Snake#5099
2019-05-04 21:42:15,616 - discord.client - WARNING - PyNaCl is not installed, voice will NOT be supported
2019-05-04 21:42:15,619 - db_handler - INFO - Init DB connection
2019-05-04 21:42:15,632 - db_handler - INFO - Init DB connection
2019-05-04 21:42:15,795 - db_handler - INFO - Init DB connection
2019-05-04 21:42:15,814 - discord.client - INFO - logging in using static token
2019-05-04 21:42:17,079 - discord.gateway - INFO - Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
2019-05-04 21:42:17,084 - discord.gateway - INFO - Shard ID None has sent the IDENTIFY payload.
2019-05-04 21:42:17,256 - discord.gateway - INFO - Shard ID None has connected to Gateway: gateway-prd-main-98g6, discord-sessions-prd-1-27 (Session ID: 7617e2a6ae84a51abaf976aca4776be5).
2019-05-04 21:42:19,262 - __main__ - INFO - We have logged in as Snake#5099
2019-05-04 21:52:39,549 - discord.client - WARNING - PyNaCl is not installed, voice will NOT be supported
2019-05-04 21:52:39,556 - db_handler - INFO - Init DB connection
2019-05-04 21:52:39,573 - db_handler - INFO - Init DB connection
2019-05-04 21:52:39,748 - db_handler - INFO - Init DB connection
2019-05-04 21:52:39,774 - discord.client - INFO - logging in using static token
2019-05-04 21:52:41,101 - discord.gateway - INFO - Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
2019-05-04 21:52:41,119 - discord.gateway - INFO - Shard ID None has sent the IDENTIFY payload.
2019-05-04 21:52:41,409 - discord.gateway - INFO - Shard ID None has connected to Gateway: gateway-prd-main-0q5p, discord-sessions-prd-1-26 (Session ID: 20b6cbb3c69ec06c8e73104ed7a2c8cc).
2019-05-04 21:52:43,419 - __main__ - INFO - We have logged in as Snake#5099
2019-05-04 21:53:27,369 - discord.gateway - WARNING - Heartbeat blocked for more than 5 seconds.
2019-05-04 21:53:32,376 - discord.gateway - WARNING - Heartbeat blocked for more than 10 seconds.
2019-05-04 21:53:37,382 - discord.gateway - WARNING - Heartbeat blocked for more than 15 seconds.
2019-05-04 21:53:43,183 - discord.gateway - INFO - Websocket closed with 1000 (), cannot reconnect.
2019-05-04 21:53:43,187 - discord.client - ERROR - Attempting a reconnect in 1.01s
Traceback (most recent call last):
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\discord\gateway.py", line 464, in poll_event
    msg = await self.recv()
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\websockets\protocol.py", line 350, in recv
    yield from self.ensure_open()
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\websockets\protocol.py", line 512, in ensure_open
    self.close_code, self.close_reason) from self.transfer_data_exc
websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1000 (OK), no reason

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\discord\client.py", line 431, in connect
    await self._connect()
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\discord\client.py", line 395, in _connect
    await self.ws.poll_event()
  File "F:\_DEV\Envs\SnakeBot\lib\site-packages\discord\gateway.py", line 472, in poll_event
    raise ConnectionClosed(exc, shard_id=self.shard_id) from exc
discord.errors.ConnectionClosed: WebSocket connection is closed: code = 1000 (OK), no reason
2019-05-04 21:55:14,932 - discord.client - WARNING - PyNaCl is not installed, voice will NOT be supported
2019-05-04 21:55:14,934 - db_handler - INFO - Init DB connection
2019-05-04 21:55:14,943 - db_handler - INFO - Init DB connection
2019-05-04 21:55:15,046 - db_handler - INFO - Init DB connection
2019-05-04 21:55:15,058 - discord.client - INFO - logging in using static token
2019-05-04 21:55:16,092 - discord.gateway - INFO - Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
2019-05-04 21:55:16,100 - discord.gateway - INFO - Shard ID None has sent the IDENTIFY payload.
2019-05-04 21:55:16,265 - discord.gateway - INFO - Shard ID None has connected to Gateway: gateway-prd-main-lzc4, discord-sessions-prd-1-23 (Session ID: bf460a811ddf3228d2050d11984fa06d).
2019-05-04 21:55:18,272 - __main__ - INFO - We have logged in as Snake#5099
2019-05-04 21:56:46,025 - discord.client - WARNING - PyNaCl is not installed, voice will NOT be supported
2019-05-04 21:56:46,028 - db_handler - INFO - Init DB connection
2019-05-04 21:56:46,038 - db_handler - INFO - Init DB connection
2019-05-04 21:56:46,145 - db_handler - INFO - Init DB connection
2019-05-04 21:56:46,157 - discord.client - INFO - logging in using static token
2019-05-04 21:56:47,255 - discord.gateway - INFO - Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
2019-05-04 21:56:47,260 - discord.gateway - INFO - Shard ID None has sent the IDENTIFY payload.
2019-05-04 21:56:47,513 - discord.gateway - INFO - Shard ID None has connected to Gateway: gateway-prd-main-bm08, discord-sessions-prd-1-22 (Session ID: acdfbbf1ab241f86b0f21e5639a68d6b).
2019-05-04 21:56:49,521 - __main__ - INFO - We have logged in as Snake#5099
2019-05-04 21:58:03,489 - discord.client - WARNING - PyNaCl is not installed, voice will NOT be supported
2019-05-04 21:58:03,492 - db_handler - INFO - Init DB connection
2019-05-04 21:58:03,500 - db_handler - INFO - Init DB connection
2019-05-04 21:58:03,680 - db_handler - INFO - Init DB connection
2019-05-04 21:58:03,713 - discord.client - INFO - logging in using static token
2019-05-04 21:58:04,753 - discord.gateway - INFO - Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
2019-05-04 21:58:04,757 - discord.gateway - INFO - Shard ID None has sent the IDENTIFY payload.
2019-05-04 21:58:04,937 - discord.gateway - INFO - Shard ID None has connected to Gateway: gateway-prd-main-xt1j, discord-sessions-prd-1-14 (Session ID: 93ffdd1cbb8e50c6a4a9d1522494312a).
2019-05-04 21:58:06,941 - __main__ - INFO - We have logged in as Snake#5099
2019-05-04 22:03:12,024 - db_handler - INFO - {'ally_code': 376764962} found for 143651954919342080
2019-05-04 22:03:13,622 - swgoh_handler - INFO - Response 200 OK
2019-05-04 22:03:13,643 - db_handler - INFO - User update DONE with new 2019-05-04 progress data
2019-05-04 22:03:26,766 - db_handler - INFO - {'ally_code': 567793738} found for 396358001646108691
2019-05-04 22:03:28,191 - swgoh_handler - INFO - Response 200 OK
2019-05-04 22:03:28,216 - db_handler - INFO - User update DONE with new 2019-05-04 progress data
2019-05-04 22:03:37,508 - db_handler - INFO - {'ally_code': 471941296} found for 269074011185610762
2019-05-04 22:03:38,942 - swgoh_handler - INFO - Response 200 OK
2019-05-04 22:03:38,989 - db_handler - INFO - User update DONE with new 2019-05-04 progress data
2019-05-04 22:03:54,060 - db_handler - INFO - {'ally_code': 999134554} found for 353891399550238721
2019-05-04 22:03:55,689 - swgoh_handler - INFO - Response 200 OK
2019-05-04 22:03:55,726 - db_handler - INFO - User update DONE with new 2019-05-04 progress data
